/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VocabContextGenerator
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiProvider: "anthropic",
  apiKey: "",
  apiEndpoint: "https://api.anthropic.com/v1/messages",
  model: "claude-3-5-sonnet-20241022",
  articleStyle: "story",
  articleLength: 300,
  maxVocabCount: 100,
  outputFolder: "D.\u8D44\u6E90/\u751F\u6210\u7684\u8BED\u5883\u6587\u7AE0"
};
var VocabContextGenerator = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "generate-vocab-article",
      name: "\u751F\u6210\u751F\u8BCD\u6587\u7AE0",
      callback: async () => {
        await this.generateArticleFromCurrentNote();
      }
    });
    this.addSettingTab(new VocabGeneratorSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async generateArticleFromCurrentNote() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view) {
      new import_obsidian.Notice("\u274C \u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u7B14\u8BB0");
      return;
    }
    const file = view.file;
    if (!file) {
      new import_obsidian.Notice("\u274C \u65E0\u6CD5\u83B7\u53D6\u5F53\u524D\u6587\u4EF6");
      return;
    }
    new import_obsidian.Notice(`\u{1F680} \u6B63\u5728\u5904\u7406\u7B14\u8BB0: "${file.basename}"
\u8BF7\u7A0D\u5019...`, 5e3);
    try {
      const content = await this.app.vault.read(file);
      if (!content || content.trim().length === 0) {
        new import_obsidian.Notice("\u274C \u7B14\u8BB0\u5185\u5BB9\u4E3A\u7A7A");
        return;
      }
      if (!this.settings.apiKey) {
        new import_obsidian.Notice("\u274C \u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E API Key");
        return;
      }
      const vocabList = this.extractVocabularyFromNote(content);
      if (vocabList.length === 0) {
        new import_obsidian.Notice("\u274C \u672A\u627E\u5230\u53EF\u751F\u6210\u6587\u7AE0\u7684\u751F\u8BCD\uFF0C\u8BF7\u68C0\u67E5\u7B14\u8BB0\u5185\u5BB9\u6216\u683C\u5F0F");
        return;
      }
      const vocabBatches = this.chunkArray(vocabList, this.getBatchSize());
      new import_obsidian.Notice(`\u{1F9E0} \u5DF2\u8BC6\u522B ${vocabList.length} \u4E2A\u751F\u8BCD\uFF0C\u5C06\u5206 ${vocabBatches.length} \u7BC7\u751F\u6210`, 5e3);
      const articles = [];
      for (let index = 0; index < vocabBatches.length; index++) {
        const partNumber = index + 1;
        new import_obsidian.Notice(`\u270D\uFE0F \u6B63\u5728\u751F\u6210 Part ${partNumber}/${vocabBatches.length}...`, 2500);
        const contentForPart = await this.generateArticlePartWithAI(
          content,
          vocabBatches[index],
          partNumber,
          vocabBatches.length
        );
        articles.push({
          partNumber,
          vocabBatch: vocabBatches[index],
          content: contentForPart
        });
      }
      await this.saveArticle(file, articles, vocabList.length);
      new import_obsidian.Notice(`\u2705 \u6587\u7AE0\u751F\u6210\u6210\u529F\uFF01\u5171\u751F\u6210 ${articles.length} \u7BC7`, 5e3);
    } catch (error) {
      console.error("\u751F\u6210\u6587\u7AE0\u5931\u8D25:", error);
      new import_obsidian.Notice(`\u274C \u751F\u6210\u5931\u8D25: ${error.message}`);
    }
  }
  getBatchSize() {
    const batchSize = Number(this.settings.maxVocabCount);
    if (!Number.isFinite(batchSize) || batchSize <= 0) {
      return DEFAULT_SETTINGS.maxVocabCount;
    }
    return Math.max(1, Math.floor(batchSize));
  }
  extractVocabularyFromNote(noteContent) {
    const vocabList = [];
    const seen = /* @__PURE__ */ new Set();
    const addCandidate = (candidate) => {
      if (!candidate) {
        return;
      }
      const normalizedKey = candidate.toLowerCase();
      if (seen.has(normalizedKey)) {
        return;
      }
      seen.add(normalizedKey);
      vocabList.push(candidate);
    };
    const highlightedRegex = /==\s*([^=\n]+?)\s*==/g;
    let highlightMatch;
    while ((highlightMatch = highlightedRegex.exec(noteContent)) !== null) {
      addCandidate(this.normalizeVocabCandidate(highlightMatch[1]));
    }
    const lines = noteContent.split(/\r?\n/);
    let insideCodeBlock = false;
    for (const rawLine of lines) {
      const trimmedLine = rawLine.trim();
      if (trimmedLine.startsWith("```")) {
        insideCodeBlock = !insideCodeBlock;
        continue;
      }
      if (insideCodeBlock || !trimmedLine || trimmedLine === "---") {
        continue;
      }
      addCandidate(this.extractVocabularyCandidateFromLine(rawLine));
    }
    return vocabList;
  }
  extractVocabularyCandidateFromLine(rawLine) {
    var _a;
    const structuredLine = /^\s*(?:[-*+]\s+|\d+[.)]\s+|>\s+|\[[ xX]\]\s+)/.test(rawLine);
    const cleanedLine = this.cleanLineForVocabExtraction(rawLine);
    if (!cleanedLine || !/[A-Za-z]/.test(cleanedLine) || /https?:\/\//i.test(cleanedLine)) {
      return null;
    }
    const containsCjk = /[\u3400-\u9fff]/.test(cleanedLine);
    const hasDelimiter = /[-—:：]|[（()]/.test(cleanedLine) || /\t/.test(cleanedLine);
    const englishTokens = (_a = cleanedLine.match(/[A-Za-z][A-Za-z'’/-]*/g)) != null ? _a : [];
    if (!structuredLine && !containsCjk && !hasDelimiter && englishTokens.length > 3) {
      return null;
    }
    if (!structuredLine && !containsCjk && !hasDelimiter && englishTokens.length > 1 && /^[A-Z]/.test(cleanedLine)) {
      return null;
    }
    const candidate = this.extractLeadingVocabCandidate(cleanedLine);
    return this.normalizeVocabCandidate(candidate);
  }
  cleanLineForVocabExtraction(rawLine) {
    return rawLine.replace(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g, "$1").replace(/`+/g, "").replace(/^\s*#+\s*/, "").replace(/^\s*>\s*/, "").replace(/^\s*[-*+]\s+\[[ xX]\]\s*/, "").replace(/^\s*[-*+]\s*/, "").replace(/^\s*\d+[.)]\s*/, "").trim();
  }
  extractLeadingVocabCandidate(line) {
    const leadingMatch = line.match(/^([A-Za-z][A-Za-z'’/-]*(?:\s+[A-Za-z][A-Za-z'’/-]*){0,7})(?=\s*(?:$|[-—:：]|[（(]|[,，;/]|[\u3400-\u9fff]|(?:n|v|adj|adv|vt|vi|prep|phr|phrase|verb|noun|idiom)\.?\b))/i);
    if (leadingMatch) {
      return leadingMatch[1];
    }
    const plainPhraseMatch = line.match(/^([A-Za-z][A-Za-z'’/-]*(?:\s+[A-Za-z][A-Za-z'’/-]*){0,2})$/);
    if (plainPhraseMatch) {
      return plainPhraseMatch[1];
    }
    return null;
  }
  normalizeVocabCandidate(candidate) {
    if (!candidate) {
      return null;
    }
    const normalized = candidate.replace(/^[-—:：,;、.\s"'“”‘’()（）\[\]]+/, "").replace(/[-—:：,;、.\s"'“”‘’()（）\[\]]+$/, "").replace(/\s+(?:n|v|adj|adv|vt|vi|prep|phr|phrase|verb|noun|idiom)\.?$/i, "").replace(/\s+/g, " ").trim();
    if (!normalized) {
      return null;
    }
    if (!/^[A-Za-z][A-Za-z'’/-]*(?:\s+[A-Za-z][A-Za-z'’/-]*){0,7}$/.test(normalized)) {
      return null;
    }
    return normalized;
  }
  chunkArray(items, chunkSize) {
    const result = [];
    for (let index = 0; index < items.length; index += chunkSize) {
      result.push(items.slice(index, index + chunkSize));
    }
    return result;
  }
  async generateArticlePartWithAI(noteContent, vocabBatch, partNumber, totalParts) {
    const stylePrompt = this.getStylePrompt();
    const length = this.settings.articleLength;
    const systemPrompt = `\u4F60\u662F\u4E00\u4F4D\u4E13\u4E1A\u7684\u82F1\u8BED\u6559\u5B66\u4E13\u5BB6\u3002\u7528\u6237\u4F1A\u63D0\u4F9B\uFF1A
1. \u539F\u59CB\u7B14\u8BB0\u5185\u5BB9\uFF08\u4EC5\u7528\u4E8E\u7406\u89E3\u4E3B\u9898\u548C\u8BED\u5883\uFF09
2. \u5F53\u524D\u6279\u6B21\u5FC5\u987B\u4F7F\u7528\u7684\u82F1\u8BED\u751F\u8BCD\u5217\u8868
3. \u5F53\u524D Part \u7F16\u53F7

\u4F60\u7684\u4EFB\u52A1\u662F\uFF1A\u4EC5\u56F4\u7ED5\u5F53\u524D\u6279\u6B21\u7684\u751F\u8BCD\uFF0C\u521B\u4F5C\u4E00\u7BC7\u82F1\u8BED${stylePrompt}\u3002

\u3010\u786C\u6027\u8981\u6C42\u3011
1. \u5FC5\u987B\u4F18\u5148\u8986\u76D6\u5F53\u524D\u6279\u6B21\u4E2D\u5217\u51FA\u7684\u6240\u6709\u751F\u8BCD\u6216\u77ED\u8BED\uFF0C\u6BCF\u4E2A\u8BCD\u5C3D\u91CF\u81F3\u5C11\u4F7F\u7528\u4E00\u6B21\u3002
2. \u5FC5\u987B\u5C06\u5F53\u524D\u6279\u6B21\u4E2D\u5B9E\u9645\u4F7F\u7528\u5230\u7684\u751F\u8BCD\u7528\u53CC\u661F\u53F7\u52A0\u7C97\uFF0C\u4F8B\u5982\uFF1A**word**\u3002
3. \u4E0D\u8981\u8F93\u51FA\u6807\u9898\u3001Part \u6807\u9898\u3001\u8BF4\u660E\u3001\u8BCD\u8868\u3001\u6CE8\u91CA\u3001\u5F00\u573A\u767D\u6216\u603B\u7ED3\u3002
4. \u4E0D\u8981\u89E3\u91CA\u4E2D\u6587\uFF0C\u4E5F\u4E0D\u8981\u6DF7\u5165\u5176\u4ED6\u6279\u6B21\u7684\u751F\u8BCD\u3002
5. \u6587\u7AE0\u76EE\u6807\u957F\u5EA6\u7EA6 ${length} \u8BCD\uFF1B\u5982\u679C\u4E3A\u4E86\u81EA\u7136\u8986\u76D6\u5168\u90E8\u751F\u8BCD\uFF0C\u53EF\u4EE5\u9002\u5EA6\u8D85\u8FC7\u3002
6. \u53EA\u8F93\u51FA\u6B63\u6587\u5185\u5BB9\uFF0C\u4F7F\u7528\u7EAF Markdown \u6BB5\u843D\uFF0C\u4E0D\u8981\u653E\u8FDB\u4EE3\u7801\u5757\u3002`;
    const userPrompt = `\u5F53\u524D\u90E8\u5206\uFF1APart ${partNumber}/${totalParts}

\u3010\u672C\u6279\u5FC5\u987B\u4F7F\u7528\u7684\u751F\u8BCD\u3011
${vocabBatch.map((word, index) => `${index + 1}. ${word}`).join("\n")}

\u3010\u539F\u59CB\u7B14\u8BB0\u5185\u5BB9\u3011
${noteContent}

\u8BF7\u76F4\u63A5\u8F93\u51FA\u6B63\u6587\u3002`;
    let responseText = "";
    if (this.settings.apiProvider === "anthropic") {
      responseText = await this.callAnthropicAPI(systemPrompt, userPrompt);
    } else if (this.settings.apiProvider === "openai") {
      responseText = await this.callOpenAIAPI(systemPrompt, userPrompt);
    } else if (this.settings.apiProvider === "deepseek") {
      responseText = await this.callDeepSeekAPI(systemPrompt, userPrompt);
    } else {
      responseText = await this.callCustomAPI(systemPrompt, userPrompt);
    }
    return this.sanitizeArticleContent(responseText);
  }
  sanitizeArticleContent(article) {
    let cleaned = article.trim();
    cleaned = cleaned.replace(/^```(?:markdown)?\s*/i, "").replace(/\s*```$/i, "").trim();
    cleaned = cleaned.replace(/^(?:#\s*)?Part\s*\d+\s*\n+/i, "");
    cleaned = cleaned.replace(/^(?:以下是.*|下面是.*|这是.*|Here(?:'s| is).*)\n+/i, "");
    return cleaned.trim();
  }
  getStylePrompt() {
    const styles = {
      story: "\u77ED\u7BC7\u6545\u4E8B",
      news: "\u65B0\u95FB\u62A5\u9053",
      dialogue: "\u5BF9\u8BDD",
      essay: "\u77ED\u6587"
    };
    return styles[this.settings.articleStyle] || "\u77ED\u6587";
  }
  async callAnthropicAPI(systemPrompt, userPrompt) {
    const response = await (0, import_obsidian.requestUrl)({
      url: this.settings.apiEndpoint,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.settings.apiKey,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: this.settings.model,
        max_tokens: 4e3,
        system: systemPrompt,
        messages: [
          {
            role: "user",
            content: userPrompt
          }
        ]
      })
    });
    if (response.status !== 200) {
      throw new Error(`API\u8C03\u7528\u5931\u8D25: ${response.status} ${response.text}`);
    }
    const data = response.json;
    return data.content[0].text;
  }
  async callOpenAIAPI(systemPrompt, userPrompt) {
    const response = await (0, import_obsidian.requestUrl)({
      url: this.settings.apiEndpoint || "https://api.openai.com/v1/chat/completions",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.settings.apiKey}`
      },
      body: JSON.stringify({
        model: this.settings.model || "gpt-4",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ],
        max_tokens: 4e3
      })
    });
    if (response.status !== 200) {
      throw new Error(`API\u8C03\u7528\u5931\u8D25: ${response.status} ${response.text}`);
    }
    const data = response.json;
    return data.choices[0].message.content;
  }
  async callDeepSeekAPI(systemPrompt, userPrompt) {
    const response = await (0, import_obsidian.requestUrl)({
      url: this.settings.apiEndpoint || "https://api.deepseek.com/v1/chat/completions",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.settings.apiKey}`
      },
      body: JSON.stringify({
        model: this.settings.model || "deepseek-chat",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ],
        max_tokens: 4e3
      })
    });
    if (response.status !== 200) {
      throw new Error(`API\u8C03\u7528\u5931\u8D25: ${response.status} ${response.text}`);
    }
    const data = response.json;
    return data.choices[0].message.content;
  }
  async callCustomAPI(systemPrompt, userPrompt) {
    const response = await (0, import_obsidian.requestUrl)({
      url: this.settings.apiEndpoint,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.settings.apiKey}`
      },
      body: JSON.stringify({
        model: this.settings.model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ]
      })
    });
    if (response.status !== 200) {
      throw new Error(`API\u8C03\u7528\u5931\u8D25: ${response.status} ${response.text}`);
    }
    return response.text;
  }
  async ensureFolderExists(folderPath) {
    const normalizedFolder = (0, import_obsidian.normalizePath)(folderPath.trim());
    if (!normalizedFolder || normalizedFolder === ".") {
      return;
    }
    const segments = normalizedFolder.split("/").filter(Boolean);
    let currentPath = "";
    for (const segment of segments) {
      currentPath = currentPath ? `${currentPath}/${segment}` : segment;
      if (!await this.app.vault.adapter.exists(currentPath)) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
  buildCombinedArticleContent(sourceFile, articles, totalVocabCount) {
    const generatedAt = new Date().toISOString();
    const batchSize = this.getBatchSize();
    const articleBody = articles.map((article) => `# Part${article.partNumber}

${article.content.trim()}`).join("\n\n---\n\n");
    return `---
source: "[[${sourceFile.path}]]"
generated: ${generatedAt}
article_style: ${this.settings.articleStyle}
model: ${this.settings.model}
vocab_count: ${totalVocabCount}
part_count: ${articles.length}
max_vocab_per_part: ${batchSize}
---

## \u751F\u8BCD\u8BED\u5883\u6587\u7AE0 (AI \u751F\u6210)

> \u672C\u6587\u4EF6\u57FA\u4E8E [[${sourceFile.path}]] \u81EA\u52A8\u751F\u6210\uFF0C\u5171 ${articles.length} \u7BC7\u6587\u7AE0\uFF0C\u6309\u6BCF\u7BC7\u6700\u591A ${batchSize} \u4E2A\u751F\u8BCD\u62C6\u5206\u3002

${articleBody}

---

## \u5B66\u4E60\u63D0\u793A

1. \u6BCF\u4E2A Part \u5BF9\u5E94\u4E00\u6279\u751F\u8BCD\uFF0C\u9002\u5408\u5206\u6B21\u9605\u8BFB\u548C\u590D\u4E60\u3002
2. \u672C\u6587\u4E2D\u7684**\u52A0\u7C97\u90E8\u5206**\u5373\u4E3A\u5F53\u524D\u6279\u6B21\u91CD\u70B9\u7EC3\u4E60\u7684\u751F\u8BCD\u6216\u8BCD\u7EC4\u3002
3. \u5982\u679C\u5355\u7BC7\u751F\u8BCD\u8FC7\u591A\uFF0C\u53EF\u5728\u8BBE\u7F6E\u4E2D\u7EE7\u7EED\u8C03\u5C0F\u201C\u6BCF\u7BC7\u6700\u5927\u751F\u8BCD\u6570\u201D\u3002
`;
  }
  async saveArticle(sourceFile, articles, totalVocabCount) {
    const outputFolder = (0, import_obsidian.normalizePath)(this.settings.outputFolder.trim());
    if (outputFolder && outputFolder !== ".") {
      await this.ensureFolderExists(outputFolder);
    }
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
    const fileName = outputFolder && outputFolder !== "." ? `${outputFolder}/${sourceFile.basename}-AI-${timestamp}.md` : `${sourceFile.basename}-AI-${timestamp}.md`;
    const fileContent = this.buildCombinedArticleContent(sourceFile, articles, totalVocabCount);
    const newFile = await this.app.vault.create(fileName, fileContent);
    await this.app.workspace.getLeaf("tab").openFile(newFile);
  }
};
var VocabGeneratorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u751F\u8BCD\u6587\u7AE0\u751F\u6210\u5668 - \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("API\u63D0\u4F9B\u5546").setDesc("\u9009\u62E9\u4F7F\u7528\u7684AI\u670D\u52A1\u63D0\u4F9B\u5546").addDropdown((dropdown) => dropdown.addOption("anthropic", "Anthropic (Claude)").addOption("openai", "OpenAI (GPT)").addOption("deepseek", "DeepSeek").addOption("custom", "\u81EA\u5B9A\u4E49API").setValue(this.plugin.settings.apiProvider).onChange(async (value) => {
      this.plugin.settings.apiProvider = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u8F93\u5165\u4F60\u7684API\u5BC6\u94A5").addText((text) => text.setPlaceholder("sk-xxx...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
    if (this.plugin.settings.apiProvider === "custom" || this.plugin.settings.apiProvider === "openai" || this.plugin.settings.apiProvider === "deepseek") {
      let placeholder = "https://api.example.com/v1/chat";
      if (this.plugin.settings.apiProvider === "openai") {
        placeholder = "https://api.openai.com/v1/chat/completions";
      } else if (this.plugin.settings.apiProvider === "deepseek") {
        placeholder = "https://api.deepseek.com/v1/chat/completions";
      }
      new import_obsidian.Setting(containerEl).setName("API\u7AEF\u70B9").setDesc("API\u8C03\u7528\u5730\u5740\uFF08\u53EF\u9009\uFF0C\u7559\u7A7A\u4F7F\u7528\u9ED8\u8BA4\u5730\u5740\uFF09").addText((text) => text.setPlaceholder(placeholder).setValue(this.plugin.settings.apiEndpoint).onChange(async (value) => {
        this.plugin.settings.apiEndpoint = value;
        await this.plugin.saveSettings();
      }));
    }
    const modelSetting = new import_obsidian.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u9009\u62E9AI\u6A21\u578B");
    const modelOptions = {
      anthropic: {
        "claude-3-5-sonnet-20241022": "Claude 3.5 Sonnet\uFF08\u63A8\u8350\uFF09",
        custom: "\u81EA\u5B9A\u4E49..."
      },
      openai: {
        "gpt-4o": "GPT-4o\uFF08\u63A8\u8350\uFF09",
        "gpt-4o-mini": "GPT-4o Mini\uFF08\u7ECF\u6D4E\uFF09",
        custom: "\u81EA\u5B9A\u4E49..."
      },
      deepseek: {
        "deepseek-chat": "DeepSeek Chat\uFF08\u63A8\u8350\uFF09",
        custom: "\u81EA\u5B9A\u4E49..."
      },
      custom: {
        custom: "\u81EA\u5B9A\u4E49\u6A21\u578B"
      }
    };
    const currentProvider = this.plugin.settings.apiProvider;
    const options = modelOptions[currentProvider] || modelOptions.custom;
    const currentModel = this.plugin.settings.model;
    const isCustomModel = !Object.keys(options).includes(currentModel);
    modelSetting.addDropdown((dropdown) => {
      for (const [value, label] of Object.entries(options)) {
        dropdown.addOption(value, label);
      }
      if (isCustomModel) {
        dropdown.setValue("custom");
      } else {
        dropdown.setValue(currentModel);
      }
      dropdown.onChange(async (value) => {
        if (value !== "custom") {
          this.plugin.settings.model = value;
          await this.plugin.saveSettings();
          this.display();
        } else {
          this.display();
        }
      });
    });
    if (isCustomModel || currentModel === "custom") {
      new import_obsidian.Setting(containerEl).setName("\u81EA\u5B9A\u4E49\u6A21\u578B\u540D\u79F0").addText((text) => text.setPlaceholder("\u4F8B\u5982: gpt-4").setValue(isCustomModel ? currentModel : "").onChange(async (value) => {
        if (value.trim()) {
          this.plugin.settings.model = value.trim();
          await this.plugin.saveSettings();
        }
      }));
    }
    containerEl.createEl("h3", { text: "\u6587\u7AE0\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u6587\u7AE0\u4F53\u88C1").addDropdown((dropdown) => dropdown.addOption("story", "\u6545\u4E8B").addOption("news", "\u65B0\u95FB").addOption("dialogue", "\u5BF9\u8BDD").addOption("essay", "\u77ED\u6587").setValue(this.plugin.settings.articleStyle).onChange(async (value) => {
      this.plugin.settings.articleStyle = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6587\u7AE0\u957F\u5EA6").setDesc("\u76EE\u6807\u5B57\u6570\uFF08\u82F1\u6587\u5355\u8BCD\u6570\uFF09").addText((text) => text.setValue(String(this.plugin.settings.articleLength)).onChange(async (value) => {
      const num = parseInt(value, 10);
      if (!isNaN(num) && num > 0) {
        this.plugin.settings.articleLength = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("\u6BCF\u7BC7\u6700\u5927\u751F\u8BCD\u6570").setDesc("\u6BCF\u7BC7\u6587\u7AE0\u6700\u591A\u5305\u542B\u591A\u5C11\u4E2A\u751F\u8BCD\uFF1B\u8D85\u8FC7\u65F6\u4F1A\u81EA\u52A8\u62C6\u6210\u591A\u7BC7\u3002\u5EFA\u8BAE 50-80\u3002").addText((text) => text.setValue(String(this.plugin.settings.maxVocabCount)).onChange(async (value) => {
      const num = parseInt(value, 10);
      if (!isNaN(num) && num > 0) {
        this.plugin.settings.maxVocabCount = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("\u8F93\u51FA\u6587\u4EF6\u5939").addText((text) => text.setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createDiv().innerHTML = "<br><b>\u63D0\u793A\uFF1A</b> \u63D2\u4EF6\u4F1A\u5148\u63D0\u53D6\u7B14\u8BB0\u4E2D\u7684\u751F\u8BCD\uFF0C\u518D\u6309\u201C\u6BCF\u7BC7\u6700\u5927\u751F\u8BCD\u6570\u201D\u81EA\u52A8\u62C6\u5206\u4E3A\u591A\u7BC7\u6587\u7AE0\uFF0C\u5E76\u5408\u5E76\u4FDD\u5B58\u4E3A\u4E00\u4E2A Markdown \u6587\u4EF6\u3002";
  }
};
