/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SweeperPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/rules/tabsToSpaces.ts
function convertLeadingTabsToSpaces(content) {
  let changesCount = 0;
  const result = content.replace(/^(\t+)/gm, (match) => {
    changesCount++;
    return "  ".repeat(match.length);
  });
  return { content: result, changesCount };
}
var tabsToSpacesRule = {
  id: "tabsToSpaces",
  name: "Tabs to spaces",
  group: "whitespace",
  tier: "standard",
  example: "\u2192item \u2192 \xB7\xB7item",
  fn: convertLeadingTabsToSpaces
};

// src/rules/trailingWhitespace.ts
function removeTrailingWhitespaceContent(content) {
  let changesCount = 0;
  const result = content.replace(/^(.*\S)([ \t]+)$/gm, (match, lineContent) => {
    changesCount++;
    return lineContent;
  });
  return { content: result, changesCount };
}
function removeTrailingWhitespaceBlank(content) {
  let changesCount = 0;
  const result = content.replace(/^([ \t]+)$/gm, () => {
    changesCount++;
    return "";
  });
  return { content: result, changesCount };
}
var trailingWhitespaceContentRule = {
  id: "trailingWhitespaceContent",
  name: "Trailing whitespace",
  group: "whitespace",
  tier: "minimal",
  example: "text\xB7\xB7 \u2192 text",
  fn: removeTrailingWhitespaceContent
};
var trailingWhitespaceBlankRule = {
  id: "trailingWhitespaceBlank",
  name: "Blank line whitespace",
  group: "blankLines",
  tier: "minimal",
  example: "\xB7\xB7\xB7(empty line) \u2192 (empty line)",
  fn: removeTrailingWhitespaceBlank
};

// src/rules/leadingIndentation.ts
function removeCommonLeadingIndentation(content) {
  const lines = content.split("\n");
  let minIndent = Infinity;
  for (const line of lines) {
    if (line.trim() === "")
      continue;
    const match = line.match(/^[ \t]*/);
    const indent = match ? match[0].length : 0;
    minIndent = Math.min(minIndent, indent);
  }
  if (minIndent === 0 || minIndent === Infinity) {
    return { content, changesCount: 0 };
  }
  let changesCount = 0;
  const result = lines.map((line) => {
    if (line.trim() === "")
      return line;
    changesCount++;
    return line.slice(minIndent);
  }).join("\n");
  return { content: result, changesCount };
}
var leadingIndentationRule = {
  id: "leadingIndentation",
  name: "Common indentation",
  group: "whitespace",
  tier: "aggressive",
  example: "\xB7\xB7\xB7\xB7all lines indented \u2192 removed",
  fn: removeCommonLeadingIndentation
};

// src/rules/utils.ts
function processOutsideCode(content, processor) {
  const parts = [];
  const codePattern = /(```[\s\S]*?```|`[^`\n]+`)/g;
  let lastIndex = 0;
  let match;
  while ((match = codePattern.exec(content)) !== null) {
    if (match.index > lastIndex) {
      parts.push(processor(content.slice(lastIndex, match.index)));
    }
    parts.push(match[0]);
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < content.length) {
    parts.push(processor(content.slice(lastIndex)));
  }
  return parts.join("");
}
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// src/rules/htmlEntities.ts
function decodeHtmlEntities(content) {
  let changesCount = 0;
  const entities = {
    "&nbsp;": " ",
    "&amp;": "&",
    // Don't decode &lt; and &gt; - they're intentionally escaped to show literal < >
    // Decoding them creates text that looks like HTML tags to markdown renderers
    "&quot;": '"',
    "&#39;": "'",
    "&apos;": "'"
  };
  const result = processOutsideCode(content, (text) => {
    let processed = text;
    for (const [entity, char] of Object.entries(entities)) {
      const regex = new RegExp(escapeRegex(entity), "gi");
      processed = processed.replace(regex, () => {
        changesCount++;
        return char;
      });
    }
    return processed;
  });
  return { content: result, changesCount };
}
var htmlEntitiesRule = {
  id: "htmlEntities",
  name: "HTML entities",
  group: "html",
  tier: "standard",
  example: "&amp; \u2192 &",
  fn: decodeHtmlEntities
};

// src/rules/htmlTags.ts
function convertKnownHtmlTags(text) {
  let changesCount = 0;
  let processed = text;
  processed = processed.replace(/<br\s*\/?>/gi, () => {
    changesCount++;
    return "\n";
  });
  processed = processed.replace(/<(b|strong)\b[^>]*>([\s\S]*?)<\/\1>/gi, (_, tag, inner) => {
    changesCount++;
    return `**${inner}**`;
  });
  processed = processed.replace(/<(i|em)\b[^>]*>([\s\S]*?)<\/\1>/gi, (_, tag, inner) => {
    changesCount++;
    return `*${inner}*`;
  });
  processed = processed.replace(/<(del|s|strike)\b[^>]*>([\s\S]*?)<\/\1>/gi, (_, tag, inner) => {
    changesCount++;
    return `~~${inner}~~`;
  });
  processed = processed.replace(/<code\b[^>]*>([\s\S]*?)<\/code>/gi, (_, inner) => {
    changesCount++;
    return `\`${inner}\``;
  });
  processed = processed.replace(/<pre\b[^>]*>([\s\S]*?)<\/pre>/gi, (_, inner) => {
    changesCount++;
    const cleaned = inner.replace(/<\/?code\b[^>]*>/gi, "");
    return "```\n" + cleaned.trim() + "\n```";
  });
  processed = processed.replace(/<a\b[^>]*href=["']([^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi, (_, url, text2) => {
    changesCount++;
    return `[${text2}](${url})`;
  });
  processed = processed.replace(/<mark\b[^>]*>([\s\S]*?)<\/mark>/gi, (_, inner) => {
    changesCount++;
    return `==${inner}==`;
  });
  processed = processed.replace(/<blockquote\b[^>]*>([\s\S]*?)<\/blockquote>/gi, (_, inner) => {
    changesCount++;
    const lines = inner.trim().split("\n");
    return lines.map((line) => `> ${line}`).join("\n");
  });
  processed = processed.replace(/<h([1-6])\b[^>]*>([\s\S]*?)<\/h\1>/gi, (_, level, inner) => {
    changesCount++;
    return "#".repeat(parseInt(level)) + " " + inner.trim();
  });
  processed = processed.replace(/<ul\b[^>]*>([\s\S]*?)<\/ul>/gi, (_, inner) => {
    changesCount++;
    return inner.replace(/<li\b[^>]*>([\s\S]*?)<\/li>/gi, (_2, li) => `- ${li.trim()}
`).trim();
  });
  processed = processed.replace(/<ol\b[^>]*>([\s\S]*?)<\/ol>/gi, (_, inner) => {
    changesCount++;
    let num = 0;
    return inner.replace(/<li\b[^>]*>([\s\S]*?)<\/li>/gi, (_2, li) => {
      num++;
      return `${num}. ${li.trim()}
`;
    }).trim();
  });
  processed = processed.replace(/<hr\s*\/?>/gi, () => {
    changesCount++;
    return "---";
  });
  processed = processed.replace(/<p\b[^>]*>([\s\S]*?)<\/p>/gi, (_, inner) => {
    changesCount++;
    return inner.trim() + "\n\n";
  });
  processed = processed.replace(/<div\b[^>]*>([\s\S]*?)<\/div>/gi, (_, inner) => {
    changesCount++;
    return inner.trim() + "\n";
  });
  const tagsToStrip = ["span", "font", "u", "ins", "small", "sub", "sup"];
  for (const tag of tagsToStrip) {
    processed = processed.replace(new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)</${tag}>`, "gi"), (_, inner) => {
      changesCount++;
      return inner;
    });
  }
  return { content: processed, changesCount };
}
function stripRemainingHtmlTags(text) {
  let changesCount = 0;
  const processed = text.replace(/<\/?[a-z][a-z0-9]*\b[^>]*>/gi, () => {
    changesCount++;
    return "";
  });
  return { content: processed, changesCount };
}
function convertHtmlToMarkdown(content) {
  let totalChanges = 0;
  const result = processOutsideCode(content, (text) => {
    const converted = convertKnownHtmlTags(text);
    totalChanges += converted.changesCount;
    return converted.content;
  });
  return { content: result, changesCount: totalChanges };
}
var htmlTagsRule = {
  id: "htmlTags",
  name: "HTML to Markdown",
  group: "html",
  tier: "standard",
  example: "<b>text</b> \u2192 **text**",
  fn: convertHtmlToMarkdown
};

// src/rules/htmlCleanupAggressive.ts
function aggressiveHtmlCleanup(content) {
  let totalChanges = 0;
  const result = processOutsideCode(content, (text) => {
    let processed = text;
    const ltCount = (processed.match(/&lt;/gi) || []).length;
    const gtCount = (processed.match(/&gt;/gi) || []).length;
    processed = processed.replace(/&lt;/gi, "<");
    processed = processed.replace(/&gt;/gi, ">");
    totalChanges += ltCount + gtCount;
    const converted = convertKnownHtmlTags(processed);
    processed = converted.content;
    totalChanges += converted.changesCount;
    const stripped = stripRemainingHtmlTags(processed);
    processed = stripped.content;
    totalChanges += stripped.changesCount;
    return processed;
  });
  return { content: result, changesCount: totalChanges };
}
var htmlCleanupAggressiveRule = {
  id: "htmlCleanupAggressive",
  name: "Aggressive HTML cleanup",
  group: "html",
  tier: "aggressive",
  example: "&lt;b&gt;text&lt;/b&gt; \u2192 **text**",
  fn: aggressiveHtmlCleanup
};

// src/rules/smartQuotes.ts
function normalizeSmartQuotes(content) {
  let changesCount = 0;
  const result = processOutsideCode(content, (text) => {
    let processed = text;
    processed = processed.replace(/[\u201c\u201d\u201e\u00ab\u00bb]/g, () => {
      changesCount++;
      return '"';
    });
    processed = processed.replace(/[\u2018\u2019\u201a\u2039\u203a]/g, () => {
      changesCount++;
      return "'";
    });
    return processed;
  });
  return { content: result, changesCount };
}
var smartQuotesRule = {
  id: "smartQuotes",
  name: "Smart quotes",
  group: "formatting",
  tier: "aggressive",
  example: '"curly" \u2192 "straight"',
  fn: normalizeSmartQuotes
};

// src/rules/linkSpaces.ts
function fixLinkSpaces(content) {
  let changesCount = 0;
  const result = content.replace(
    /\[([^\]]+)\]\s+\(([^)]+)\)/g,
    (match, text, url) => {
      changesCount++;
      return `[${text}](${url})`;
    }
  );
  return { content: result, changesCount };
}
var linkSpacesRule = {
  id: "linkSpaces",
  name: "Link spaces",
  group: "formatting",
  tier: "standard",
  example: "[text] (url) \u2192 [text](url)",
  fn: fixLinkSpaces
};

// src/rules/headingSpaces.ts
function fixHeadingSpaces(content) {
  let changesCount = 0;
  const result = content.replace(
    /^(#{1,6})([^\s#])/gm,
    (match, hashes, firstChar) => {
      changesCount++;
      return `${hashes} ${firstChar}`;
    }
  );
  return { content: result, changesCount };
}
var headingSpacesRule = {
  id: "headingSpaces",
  name: "Heading spaces",
  group: "headings",
  tier: "standard",
  example: "##Title \u2192 ## Title",
  fn: fixHeadingSpaces
};

// src/rules/checkboxes.ts
function normalizeCheckboxes(content) {
  let changesCount = 0;
  let result = content;
  result = result.replace(/^(\s*[-*+]\s*)\[\](\s)/gm, (match, prefix, suffix) => {
    changesCount++;
    return `${prefix}[ ]${suffix}`;
  });
  result = result.replace(/^(\s*[-*+]\s*)\[X\]/gm, (match, prefix) => {
    changesCount++;
    return `${prefix}[x]`;
  });
  return { content: result, changesCount };
}
var checkboxesRule = {
  id: "checkboxes",
  name: "Checkboxes",
  group: "lists",
  tier: "standard",
  example: "- [] task \u2192 - [ ] task",
  fn: normalizeCheckboxes
};

// src/rules/multipleSpaces.ts
function collapseMultipleSpaces(content) {
  let changesCount = 0;
  const result = content.split("\n").map((line) => {
    const leadingMatch = line.match(/^(\s*)/);
    const leading = leadingMatch ? leadingMatch[0] : "";
    const rest = line.slice(leading.length);
    const collapsed = rest.replace(/ {2,}/g, () => {
      changesCount++;
      return " ";
    });
    return leading + collapsed;
  }).join("\n");
  return { content: result, changesCount };
}
var multipleSpacesRule = {
  id: "multipleSpaces",
  name: "Multiple spaces",
  group: "whitespace",
  tier: "standard",
  example: "too\xB7\xB7\xB7\xB7many \u2192 too many",
  fn: collapseMultipleSpaces
};

// src/rules/blankLines.ts
function removeBlankLinesBetweenListItems(content) {
  let changesCount = 0;
  let result = content;
  result = result.replace(
    /^(\s*[-*+]\s+.*)(\n\s*\n)+(?=\s*[-*+]\s+)/gm,
    (match, listItem) => {
      changesCount++;
      return listItem + "\n";
    }
  );
  result = result.replace(
    /^(\s*\d+\.\s+.*)(\n\s*\n)+(?=\s*\d+\.\s+)/gm,
    (match, listItem) => {
      changesCount++;
      return listItem + "\n";
    }
  );
  return { content: result, changesCount };
}
function collapseMultipleBlankLines(content) {
  let changesCount = 0;
  const result = content.replace(/\n([ \t]*\n){2,}/g, (match) => {
    changesCount++;
    return "\n\n";
  });
  return { content: result, changesCount };
}
var blankLinesBetweenListItemsRule = {
  id: "blankLinesBetweenListItems",
  name: "Blank lines in lists",
  group: "blankLines",
  tier: "aggressive",
  example: "- item1\\n\\n- item2 \u2192 - item1\\n- item2",
  fn: removeBlankLinesBetweenListItems
};
var multipleBlankLinesRule = {
  id: "multipleBlankLines",
  name: "Extra blank lines",
  group: "blankLines",
  tier: "minimal",
  example: "3+ blank lines \u2192 1 blank line",
  fn: collapseMultipleBlankLines
};

// src/rules/listMarkers.ts
function normalizeListMarkers(content) {
  let changesCount = 0;
  let result = content;
  result = result.replace(/^(\s*)[*+](\s+)/gm, (match, indent, space) => {
    changesCount++;
    return `${indent}-${space}`;
  });
  result = result.replace(/^(\s*)-(?![-\s])(.)/gm, (match, indent, char) => {
    changesCount++;
    return `${indent}- ${char}`;
  });
  result = result.replace(/^(\s*)(\d+\.)(\S)/gm, (match, indent, num, char) => {
    changesCount++;
    return `${indent}${num} ${char}`;
  });
  return { content: result, changesCount };
}
var listMarkersRule = {
  id: "listMarkers",
  name: "List markers",
  group: "lists",
  tier: "standard",
  example: "* item \u2192 - item",
  fn: normalizeListMarkers
};

// src/rules/fixIndentation.ts
var LIST_ITEM_PATTERN = /^(\s*)([-*+]|\d+\.)\s/;
var INDENT_SIZE = 2;
function fixExcessiveIndentation(content) {
  let changesCount = 0;
  const lines = content.split("\n");
  const result = [];
  const indentStack = [];
  for (const line of lines) {
    const match = line.match(LIST_ITEM_PATTERN);
    if (!match) {
      result.push(line);
      continue;
    }
    const currentIndent = match[1].length;
    const restOfLine = line.slice(currentIndent);
    while (indentStack.length > 0 && indentStack[indentStack.length - 1] >= currentIndent) {
      indentStack.pop();
    }
    const parentIndent = indentStack.length > 0 ? indentStack[indentStack.length - 1] : -INDENT_SIZE;
    const expectedIndent = parentIndent + INDENT_SIZE;
    if (currentIndent > expectedIndent) {
      changesCount++;
      result.push(" ".repeat(expectedIndent) + restOfLine);
      indentStack.push(expectedIndent);
    } else {
      result.push(line);
      indentStack.push(currentIndent);
    }
  }
  return { content: result.join("\n"), changesCount };
}
var fixIndentationRule = {
  id: "fixIndentation",
  name: "Broken indentation",
  group: "lists",
  tier: "standard",
  example: "\xB7\xB7\xB7\xB7\xB7\xB7\xB7\xB7- item \u2192 \xB7\xB7- item",
  fn: fixExcessiveIndentation
};

// src/rules/emptyListItems.ts
var EMPTY_LIST_ITEM_PATTERN = /^(\s*)([-*+]|\d+\.)\s*$/;
var LIST_ITEM_PATTERN2 = /^(\s*)([-*+]|\d+\.)\s/;
function removeEmptyListItems(content) {
  let changesCount = 0;
  const lines = content.split("\n");
  const result = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const emptyMatch = line.match(EMPTY_LIST_ITEM_PATTERN);
    if (!emptyMatch) {
      result.push(line);
      continue;
    }
    const currentIndent = emptyMatch[1].length;
    const nextLine = lines[i + 1];
    if (nextLine !== void 0) {
      const nextMatch = nextLine.match(LIST_ITEM_PATTERN2);
      if (nextMatch) {
        const nextIndent = nextMatch[1].length;
        if (nextIndent > currentIndent) {
          result.push(line);
          continue;
        }
      }
    }
    changesCount++;
  }
  return { content: result.join("\n"), changesCount };
}
var emptyListItemsRule = {
  id: "emptyListItems",
  name: "Empty list items",
  group: "lists",
  tier: "standard",
  example: "- (empty) \u2192 removed",
  fn: removeEmptyListItems
};

// src/rules/eofNewline.ts
function normalizeEofNewline(content) {
  if (content === "") {
    return { content, changesCount: 0 };
  }
  const trimmed = content.replace(/[\n\r\s]+$/, "");
  const result = trimmed + "\n";
  const changesCount = result !== content ? 1 : 0;
  return { content: result, changesCount };
}
var eofNewlineRule = {
  id: "eofNewline",
  name: "EOF newline",
  group: "blankLines",
  tier: "minimal",
  example: "text\\n\\n\\n \u2192 text\\n",
  fn: normalizeEofNewline
};

// src/rules/horizontalRules.ts
function normalizeHorizontalRules(content) {
  let changesCount = 0;
  const result = content.replace(
    /^[ \t]*((\*[ \t]*){3,}|(_[ \t]*){3,}|(- [ \t]*){2,}-)[ \t]*$/gm,
    (match) => {
      if (match.trim() === "---") {
        return match;
      }
      changesCount++;
      return "---";
    }
  );
  return { content: result, changesCount };
}
function deduplicateHorizontalRules(content) {
  let changesCount = 0;
  const result = content.replace(
    /(^---[ \t]*$\n)((?:[ \t]*\n)*^---[ \t]*$\n?)+/gm,
    () => {
      changesCount++;
      return "---\n";
    }
  );
  return { content: result, changesCount };
}
var horizontalRulesRule = {
  id: "horizontalRules",
  name: "Horizontal rules",
  group: "formatting",
  tier: "aggressive",
  example: "*** \u2192 ---",
  fn: normalizeHorizontalRules
};
var horizontalRulesDedupeRule = {
  id: "horizontalRulesDedupe",
  name: "Deduplicate horizontal rules",
  group: "formatting",
  tier: "aggressive",
  example: "---,---,--- \u2192 ---",
  fn: deduplicateHorizontalRules
};

// src/rules/orderedLists.ts
function renumberOrderedLists(content) {
  let changesCount = 0;
  const lines = content.split("\n");
  const result = [];
  const counters = /* @__PURE__ */ new Map();
  let lastIndent = -1;
  for (const line of lines) {
    const match = line.match(/^(\s*)(\d+)(\.)\s/);
    if (!match) {
      if (line.trim() !== "" && !line.match(/^\s*[-*+]\s/)) {
        counters.clear();
        lastIndent = -1;
      }
      result.push(line);
      continue;
    }
    const [, indent, currentNum, dot] = match;
    const indentLevel = indent.length;
    if (indentLevel < lastIndent) {
      for (const [level] of counters) {
        if (level > indentLevel) {
          counters.delete(level);
        }
      }
    }
    let counter = counters.get(indentLevel) || 0;
    counter++;
    counters.set(indentLevel, counter);
    lastIndent = indentLevel;
    const expectedNum = counter.toString();
    if (currentNum !== expectedNum) {
      changesCount++;
      const rest = line.slice(match[0].length);
      result.push(`${indent}${expectedNum}. ${rest}`);
    } else {
      result.push(line);
    }
  }
  return { content: result.join("\n"), changesCount };
}
var orderedListsRule = {
  id: "orderedLists",
  name: "Ordered list numbers",
  group: "lists",
  tier: "standard",
  example: "1. 1. 1. \u2192 1. 2. 3.",
  fn: renumberOrderedLists
};

// src/rules/blockQuotes.ts
function cleanupBlockQuotes(content) {
  let changesCount = 0;
  const result = content.replace(/^(>+)(.*)$/gm, (match, markers, rest) => {
    const normalizedMarkers = markers.split("").join(" ");
    const trimmedRest = rest.replace(/^[ \t]*/, "");
    const normalizedLine = trimmedRest.length > 0 ? `${normalizedMarkers} ${trimmedRest}` : normalizedMarkers;
    if (match !== normalizedLine) {
      changesCount++;
      return normalizedLine;
    }
    return match;
  });
  return { content: result, changesCount };
}
var blockQuotesRule = {
  id: "blockQuotes",
  name: "Block quotes",
  group: "blockElements",
  tier: "aggressive",
  example: ">text \u2192 > text",
  fn: cleanupBlockQuotes
};

// src/rules/tagNormalization.ts
function normalizeTags(content) {
  let changesCount = 0;
  const result = processOutsideCode(content, (text) => {
    return text.replace(
      /(^|[\s,;:!?([{])#([a-zA-Z][a-zA-Z0-9_/-]*)/g,
      (match, prefix, tag) => {
        const lowercased = tag.toLowerCase();
        if (tag !== lowercased) {
          changesCount++;
          return `${prefix}#${lowercased}`;
        }
        return match;
      }
    );
  });
  return { content: result, changesCount };
}
var tagNormalizationRule = {
  id: "tagNormalization",
  name: "Tag case",
  group: "obsidian",
  tier: "aggressive",
  example: "#Tag \u2192 #tag",
  fn: normalizeTags
};

// src/rules/codeFences.ts
function normalizeCodeFences(content) {
  let changesCount = 0;
  let result = content.replace(/^(~~~+)(\w*)?$/gm, (match, tildes, lang) => {
    changesCount++;
    const backticks = "`".repeat(Math.max(3, tildes.length));
    return lang ? `${backticks}${lang}` : backticks;
  });
  return { content: result, changesCount };
}
var codeFencesRule = {
  id: "codeFences",
  name: "Code fences",
  group: "formatting",
  tier: "aggressive",
  example: "~~~ \u2192 ```",
  fn: normalizeCodeFences
};

// src/rules/emphasis.ts
function normalizeEmphasis(content) {
  let changesCount = 0;
  const result = processOutsideCode(content, (text) => {
    let processed = text;
    processed = processed.replace(/__([^_\n]+)__/g, (match, inner) => {
      changesCount++;
      return `**${inner}**`;
    });
    processed = processed.replace(
      /(^|[\s,;:!?([{])_([^_*\s][^_*]*[^_*\s])_([\s,;:!?)\]}]|$)/g,
      (match, before, inner, after) => {
        changesCount++;
        return `${before}*${inner}*${after}`;
      }
    );
    processed = processed.replace(
      /(^|[\s,;:!?([{])_([^_*\s])_([\s,;:!?)\]}]|$)/g,
      (match, before, inner, after) => {
        changesCount++;
        return `${before}*${inner}*${after}`;
      }
    );
    return processed;
  });
  return { content: result, changesCount };
}
var emphasisRule = {
  id: "emphasis",
  name: "Emphasis style",
  group: "formatting",
  tier: "aggressive",
  example: "_italic_ \u2192 *italic*",
  fn: normalizeEmphasis
};

// src/rules/headingLevels.ts
function fixHeadingLevels(content) {
  let changesCount = 0;
  const lines = content.split("\n");
  const result = [];
  let lastLevel = 0;
  for (const line of lines) {
    const match = line.match(/^(#{1,6})(\s.*)$/);
    if (!match) {
      result.push(line);
      continue;
    }
    const currentLevel = match[1].length;
    const rest = match[2];
    let targetLevel = currentLevel;
    if (lastLevel === 0) {
      targetLevel = currentLevel;
    } else if (currentLevel > lastLevel + 1) {
      targetLevel = lastLevel + 1;
      changesCount++;
    }
    lastLevel = targetLevel;
    result.push("#".repeat(targetLevel) + rest);
  }
  return { content: result.join("\n"), changesCount };
}
var headingLevelsRule = {
  id: "headingLevels",
  name: "Fix heading level gaps",
  group: "headings",
  tier: "aggressive",
  example: "# H1 \u2192 ### H3 becomes ## H2",
  fn: fixHeadingLevels
};

// src/rules/lineLeadingWhitespace.ts
function removeLineLeadingWhitespace(content) {
  let changesCount = 0;
  const lines = content.split("\n");
  const result = [];
  let inCodeBlock = false;
  for (const line of lines) {
    if (line.trim().startsWith("```")) {
      inCodeBlock = !inCodeBlock;
      result.push(line);
      continue;
    }
    if (inCodeBlock) {
      result.push(line);
      continue;
    }
    const trimmed = line.trimStart();
    if (trimmed === "" || trimmed.startsWith("-") || trimmed.startsWith("*") || trimmed.startsWith("+") || trimmed.startsWith(">") || /^\d+\./.test(trimmed)) {
      result.push(line);
      continue;
    }
    if (line !== trimmed && line.startsWith(" ") || line.startsWith("	")) {
      const leadingMatch = line.match(/^[\t ]+/);
      if (leadingMatch && !line.startsWith("    ")) {
        changesCount++;
        result.push(trimmed);
        continue;
      }
    }
    result.push(line);
  }
  return { content: result.join("\n"), changesCount };
}
var lineLeadingWhitespaceRule = {
  id: "lineLeadingWhitespace",
  name: "Line leading whitespace",
  group: "whitespace",
  tier: "aggressive",
  example: "  text \u2192 text",
  fn: removeLineLeadingWhitespace
};

// src/rules/registry.ts
var rules = [
  // Blank lines
  multipleBlankLinesRule,
  blankLinesBetweenListItemsRule,
  trailingWhitespaceBlankRule,
  eofNewlineRule,
  // Whitespace
  trailingWhitespaceContentRule,
  multipleSpacesRule,
  tabsToSpacesRule,
  leadingIndentationRule,
  // Lists
  listMarkersRule,
  checkboxesRule,
  emptyListItemsRule,
  fixIndentationRule,
  orderedListsRule,
  // Formatting
  smartQuotesRule,
  linkSpacesRule,
  horizontalRulesRule,
  horizontalRulesDedupeRule,
  emphasisRule,
  codeFencesRule,
  // Headings
  headingSpacesRule,
  headingLevelsRule,
  // HTML (standard: convert known HTML, decode safe entities)
  htmlTagsRule,
  htmlEntitiesRule,
  // HTML (aggressive: decode all entities, convert, strip remaining)
  htmlCleanupAggressiveRule,
  // Whitespace cleanup (after HTML conversion)
  lineLeadingWhitespaceRule,
  // Block elements
  blockQuotesRule,
  // Obsidian-specific
  tagNormalizationRule
];

// src/rules/index.ts
function applyAllRules(content, enabledRules) {
  let result = content;
  const results = /* @__PURE__ */ new Map();
  for (const rule of rules) {
    if (enabledRules && enabledRules[rule.id] === false) {
      continue;
    }
    const ruleResult = rule.fn(result);
    result = ruleResult.content;
    results.set(rule.id, ruleResult.changesCount);
  }
  const totalChanges = [...results.values()].reduce((a, b) => a + b, 0);
  return { content: result, summary: { results, totalChanges } };
}
function formatSummary(summary) {
  if (summary.totalChanges === 0) {
    return "No changes needed";
  }
  return `${summary.totalChanges} change${summary.totalChanges === 1 ? "" : "s"}`;
}

// src/CleanupModal.ts
var import_obsidian = require("obsidian");

// node_modules/diff/lib/index.mjs
function Diff() {
}
Diff.prototype = {
  diff: function diff(oldString, newString) {
    var _options$timeout;
    var options = arguments.length > 2 && arguments[2] !== void 0 ? arguments[2] : {};
    var callback = options.callback;
    if (typeof options === "function") {
      callback = options;
      options = {};
    }
    var self = this;
    function done(value) {
      value = self.postProcess(value, options);
      if (callback) {
        setTimeout(function() {
          callback(value);
        }, 0);
        return true;
      } else {
        return value;
      }
    }
    oldString = this.castInput(oldString, options);
    newString = this.castInput(newString, options);
    oldString = this.removeEmpty(this.tokenize(oldString, options));
    newString = this.removeEmpty(this.tokenize(newString, options));
    var newLen = newString.length, oldLen = oldString.length;
    var editLength = 1;
    var maxEditLength = newLen + oldLen;
    if (options.maxEditLength != null) {
      maxEditLength = Math.min(maxEditLength, options.maxEditLength);
    }
    var maxExecutionTime = (_options$timeout = options.timeout) !== null && _options$timeout !== void 0 ? _options$timeout : Infinity;
    var abortAfterTimestamp = Date.now() + maxExecutionTime;
    var bestPath = [{
      oldPos: -1,
      lastComponent: void 0
    }];
    var newPos = this.extractCommon(bestPath[0], newString, oldString, 0, options);
    if (bestPath[0].oldPos + 1 >= oldLen && newPos + 1 >= newLen) {
      return done(buildValues(self, bestPath[0].lastComponent, newString, oldString, self.useLongestToken));
    }
    var minDiagonalToConsider = -Infinity, maxDiagonalToConsider = Infinity;
    function execEditLength() {
      for (var diagonalPath = Math.max(minDiagonalToConsider, -editLength); diagonalPath <= Math.min(maxDiagonalToConsider, editLength); diagonalPath += 2) {
        var basePath = void 0;
        var removePath = bestPath[diagonalPath - 1], addPath = bestPath[diagonalPath + 1];
        if (removePath) {
          bestPath[diagonalPath - 1] = void 0;
        }
        var canAdd = false;
        if (addPath) {
          var addPathNewPos = addPath.oldPos - diagonalPath;
          canAdd = addPath && 0 <= addPathNewPos && addPathNewPos < newLen;
        }
        var canRemove = removePath && removePath.oldPos + 1 < oldLen;
        if (!canAdd && !canRemove) {
          bestPath[diagonalPath] = void 0;
          continue;
        }
        if (!canRemove || canAdd && removePath.oldPos < addPath.oldPos) {
          basePath = self.addToPath(addPath, true, false, 0, options);
        } else {
          basePath = self.addToPath(removePath, false, true, 1, options);
        }
        newPos = self.extractCommon(basePath, newString, oldString, diagonalPath, options);
        if (basePath.oldPos + 1 >= oldLen && newPos + 1 >= newLen) {
          return done(buildValues(self, basePath.lastComponent, newString, oldString, self.useLongestToken));
        } else {
          bestPath[diagonalPath] = basePath;
          if (basePath.oldPos + 1 >= oldLen) {
            maxDiagonalToConsider = Math.min(maxDiagonalToConsider, diagonalPath - 1);
          }
          if (newPos + 1 >= newLen) {
            minDiagonalToConsider = Math.max(minDiagonalToConsider, diagonalPath + 1);
          }
        }
      }
      editLength++;
    }
    if (callback) {
      (function exec() {
        setTimeout(function() {
          if (editLength > maxEditLength || Date.now() > abortAfterTimestamp) {
            return callback();
          }
          if (!execEditLength()) {
            exec();
          }
        }, 0);
      })();
    } else {
      while (editLength <= maxEditLength && Date.now() <= abortAfterTimestamp) {
        var ret = execEditLength();
        if (ret) {
          return ret;
        }
      }
    }
  },
  addToPath: function addToPath(path, added, removed, oldPosInc, options) {
    var last = path.lastComponent;
    if (last && !options.oneChangePerToken && last.added === added && last.removed === removed) {
      return {
        oldPos: path.oldPos + oldPosInc,
        lastComponent: {
          count: last.count + 1,
          added,
          removed,
          previousComponent: last.previousComponent
        }
      };
    } else {
      return {
        oldPos: path.oldPos + oldPosInc,
        lastComponent: {
          count: 1,
          added,
          removed,
          previousComponent: last
        }
      };
    }
  },
  extractCommon: function extractCommon(basePath, newString, oldString, diagonalPath, options) {
    var newLen = newString.length, oldLen = oldString.length, oldPos = basePath.oldPos, newPos = oldPos - diagonalPath, commonCount = 0;
    while (newPos + 1 < newLen && oldPos + 1 < oldLen && this.equals(oldString[oldPos + 1], newString[newPos + 1], options)) {
      newPos++;
      oldPos++;
      commonCount++;
      if (options.oneChangePerToken) {
        basePath.lastComponent = {
          count: 1,
          previousComponent: basePath.lastComponent,
          added: false,
          removed: false
        };
      }
    }
    if (commonCount && !options.oneChangePerToken) {
      basePath.lastComponent = {
        count: commonCount,
        previousComponent: basePath.lastComponent,
        added: false,
        removed: false
      };
    }
    basePath.oldPos = oldPos;
    return newPos;
  },
  equals: function equals(left, right, options) {
    if (options.comparator) {
      return options.comparator(left, right);
    } else {
      return left === right || options.ignoreCase && left.toLowerCase() === right.toLowerCase();
    }
  },
  removeEmpty: function removeEmpty(array) {
    var ret = [];
    for (var i = 0; i < array.length; i++) {
      if (array[i]) {
        ret.push(array[i]);
      }
    }
    return ret;
  },
  castInput: function castInput(value) {
    return value;
  },
  tokenize: function tokenize(value) {
    return Array.from(value);
  },
  join: function join(chars) {
    return chars.join("");
  },
  postProcess: function postProcess(changeObjects) {
    return changeObjects;
  }
};
function buildValues(diff2, lastComponent, newString, oldString, useLongestToken) {
  var components = [];
  var nextComponent;
  while (lastComponent) {
    components.push(lastComponent);
    nextComponent = lastComponent.previousComponent;
    delete lastComponent.previousComponent;
    lastComponent = nextComponent;
  }
  components.reverse();
  var componentPos = 0, componentLen = components.length, newPos = 0, oldPos = 0;
  for (; componentPos < componentLen; componentPos++) {
    var component = components[componentPos];
    if (!component.removed) {
      if (!component.added && useLongestToken) {
        var value = newString.slice(newPos, newPos + component.count);
        value = value.map(function(value2, i) {
          var oldValue = oldString[oldPos + i];
          return oldValue.length > value2.length ? oldValue : value2;
        });
        component.value = diff2.join(value);
      } else {
        component.value = diff2.join(newString.slice(newPos, newPos + component.count));
      }
      newPos += component.count;
      if (!component.added) {
        oldPos += component.count;
      }
    } else {
      component.value = diff2.join(oldString.slice(oldPos, oldPos + component.count));
      oldPos += component.count;
    }
  }
  return components;
}
var characterDiff = new Diff();
function diffChars(oldStr, newStr, options) {
  return characterDiff.diff(oldStr, newStr, options);
}
function longestCommonPrefix(str1, str2) {
  var i;
  for (i = 0; i < str1.length && i < str2.length; i++) {
    if (str1[i] != str2[i]) {
      return str1.slice(0, i);
    }
  }
  return str1.slice(0, i);
}
function longestCommonSuffix(str1, str2) {
  var i;
  if (!str1 || !str2 || str1[str1.length - 1] != str2[str2.length - 1]) {
    return "";
  }
  for (i = 0; i < str1.length && i < str2.length; i++) {
    if (str1[str1.length - (i + 1)] != str2[str2.length - (i + 1)]) {
      return str1.slice(-i);
    }
  }
  return str1.slice(-i);
}
function replacePrefix(string, oldPrefix, newPrefix) {
  if (string.slice(0, oldPrefix.length) != oldPrefix) {
    throw Error("string ".concat(JSON.stringify(string), " doesn't start with prefix ").concat(JSON.stringify(oldPrefix), "; this is a bug"));
  }
  return newPrefix + string.slice(oldPrefix.length);
}
function replaceSuffix(string, oldSuffix, newSuffix) {
  if (!oldSuffix) {
    return string + newSuffix;
  }
  if (string.slice(-oldSuffix.length) != oldSuffix) {
    throw Error("string ".concat(JSON.stringify(string), " doesn't end with suffix ").concat(JSON.stringify(oldSuffix), "; this is a bug"));
  }
  return string.slice(0, -oldSuffix.length) + newSuffix;
}
function removePrefix(string, oldPrefix) {
  return replacePrefix(string, oldPrefix, "");
}
function removeSuffix(string, oldSuffix) {
  return replaceSuffix(string, oldSuffix, "");
}
function maximumOverlap(string1, string2) {
  return string2.slice(0, overlapCount(string1, string2));
}
function overlapCount(a, b) {
  var startA = 0;
  if (a.length > b.length) {
    startA = a.length - b.length;
  }
  var endB = b.length;
  if (a.length < b.length) {
    endB = a.length;
  }
  var map = Array(endB);
  var k = 0;
  map[0] = 0;
  for (var j = 1; j < endB; j++) {
    if (b[j] == b[k]) {
      map[j] = map[k];
    } else {
      map[j] = k;
    }
    while (k > 0 && b[j] != b[k]) {
      k = map[k];
    }
    if (b[j] == b[k]) {
      k++;
    }
  }
  k = 0;
  for (var i = startA; i < a.length; i++) {
    while (k > 0 && a[i] != b[k]) {
      k = map[k];
    }
    if (a[i] == b[k]) {
      k++;
    }
  }
  return k;
}
var extendedWordChars = "a-zA-Z0-9_\\u{C0}-\\u{FF}\\u{D8}-\\u{F6}\\u{F8}-\\u{2C6}\\u{2C8}-\\u{2D7}\\u{2DE}-\\u{2FF}\\u{1E00}-\\u{1EFF}";
var tokenizeIncludingWhitespace = new RegExp("[".concat(extendedWordChars, "]+|\\s+|[^").concat(extendedWordChars, "]"), "ug");
var wordDiff = new Diff();
wordDiff.equals = function(left, right, options) {
  if (options.ignoreCase) {
    left = left.toLowerCase();
    right = right.toLowerCase();
  }
  return left.trim() === right.trim();
};
wordDiff.tokenize = function(value) {
  var options = arguments.length > 1 && arguments[1] !== void 0 ? arguments[1] : {};
  var parts;
  if (options.intlSegmenter) {
    if (options.intlSegmenter.resolvedOptions().granularity != "word") {
      throw new Error('The segmenter passed must have a granularity of "word"');
    }
    parts = Array.from(options.intlSegmenter.segment(value), function(segment) {
      return segment.segment;
    });
  } else {
    parts = value.match(tokenizeIncludingWhitespace) || [];
  }
  var tokens = [];
  var prevPart = null;
  parts.forEach(function(part) {
    if (/\s/.test(part)) {
      if (prevPart == null) {
        tokens.push(part);
      } else {
        tokens.push(tokens.pop() + part);
      }
    } else if (/\s/.test(prevPart)) {
      if (tokens[tokens.length - 1] == prevPart) {
        tokens.push(tokens.pop() + part);
      } else {
        tokens.push(prevPart + part);
      }
    } else {
      tokens.push(part);
    }
    prevPart = part;
  });
  return tokens;
};
wordDiff.join = function(tokens) {
  return tokens.map(function(token, i) {
    if (i == 0) {
      return token;
    } else {
      return token.replace(/^\s+/, "");
    }
  }).join("");
};
wordDiff.postProcess = function(changes, options) {
  if (!changes || options.oneChangePerToken) {
    return changes;
  }
  var lastKeep = null;
  var insertion = null;
  var deletion = null;
  changes.forEach(function(change) {
    if (change.added) {
      insertion = change;
    } else if (change.removed) {
      deletion = change;
    } else {
      if (insertion || deletion) {
        dedupeWhitespaceInChangeObjects(lastKeep, deletion, insertion, change);
      }
      lastKeep = change;
      insertion = null;
      deletion = null;
    }
  });
  if (insertion || deletion) {
    dedupeWhitespaceInChangeObjects(lastKeep, deletion, insertion, null);
  }
  return changes;
};
function dedupeWhitespaceInChangeObjects(startKeep, deletion, insertion, endKeep) {
  if (deletion && insertion) {
    var oldWsPrefix = deletion.value.match(/^\s*/)[0];
    var oldWsSuffix = deletion.value.match(/\s*$/)[0];
    var newWsPrefix = insertion.value.match(/^\s*/)[0];
    var newWsSuffix = insertion.value.match(/\s*$/)[0];
    if (startKeep) {
      var commonWsPrefix = longestCommonPrefix(oldWsPrefix, newWsPrefix);
      startKeep.value = replaceSuffix(startKeep.value, newWsPrefix, commonWsPrefix);
      deletion.value = removePrefix(deletion.value, commonWsPrefix);
      insertion.value = removePrefix(insertion.value, commonWsPrefix);
    }
    if (endKeep) {
      var commonWsSuffix = longestCommonSuffix(oldWsSuffix, newWsSuffix);
      endKeep.value = replacePrefix(endKeep.value, newWsSuffix, commonWsSuffix);
      deletion.value = removeSuffix(deletion.value, commonWsSuffix);
      insertion.value = removeSuffix(insertion.value, commonWsSuffix);
    }
  } else if (insertion) {
    if (startKeep) {
      insertion.value = insertion.value.replace(/^\s*/, "");
    }
    if (endKeep) {
      endKeep.value = endKeep.value.replace(/^\s*/, "");
    }
  } else if (startKeep && endKeep) {
    var newWsFull = endKeep.value.match(/^\s*/)[0], delWsStart = deletion.value.match(/^\s*/)[0], delWsEnd = deletion.value.match(/\s*$/)[0];
    var newWsStart = longestCommonPrefix(newWsFull, delWsStart);
    deletion.value = removePrefix(deletion.value, newWsStart);
    var newWsEnd = longestCommonSuffix(removePrefix(newWsFull, newWsStart), delWsEnd);
    deletion.value = removeSuffix(deletion.value, newWsEnd);
    endKeep.value = replacePrefix(endKeep.value, newWsFull, newWsEnd);
    startKeep.value = replaceSuffix(startKeep.value, newWsFull, newWsFull.slice(0, newWsFull.length - newWsEnd.length));
  } else if (endKeep) {
    var endKeepWsPrefix = endKeep.value.match(/^\s*/)[0];
    var deletionWsSuffix = deletion.value.match(/\s*$/)[0];
    var overlap = maximumOverlap(deletionWsSuffix, endKeepWsPrefix);
    deletion.value = removeSuffix(deletion.value, overlap);
  } else if (startKeep) {
    var startKeepWsSuffix = startKeep.value.match(/\s*$/)[0];
    var deletionWsPrefix = deletion.value.match(/^\s*/)[0];
    var _overlap = maximumOverlap(startKeepWsSuffix, deletionWsPrefix);
    deletion.value = removePrefix(deletion.value, _overlap);
  }
}
var wordWithSpaceDiff = new Diff();
wordWithSpaceDiff.tokenize = function(value) {
  var regex = new RegExp("(\\r?\\n)|[".concat(extendedWordChars, "]+|[^\\S\\n\\r]+|[^").concat(extendedWordChars, "]"), "ug");
  return value.match(regex) || [];
};
var lineDiff = new Diff();
lineDiff.tokenize = function(value, options) {
  if (options.stripTrailingCr) {
    value = value.replace(/\r\n/g, "\n");
  }
  var retLines = [], linesAndNewlines = value.split(/(\n|\r\n)/);
  if (!linesAndNewlines[linesAndNewlines.length - 1]) {
    linesAndNewlines.pop();
  }
  for (var i = 0; i < linesAndNewlines.length; i++) {
    var line = linesAndNewlines[i];
    if (i % 2 && !options.newlineIsToken) {
      retLines[retLines.length - 1] += line;
    } else {
      retLines.push(line);
    }
  }
  return retLines;
};
lineDiff.equals = function(left, right, options) {
  if (options.ignoreWhitespace) {
    if (!options.newlineIsToken || !left.includes("\n")) {
      left = left.trim();
    }
    if (!options.newlineIsToken || !right.includes("\n")) {
      right = right.trim();
    }
  } else if (options.ignoreNewlineAtEof && !options.newlineIsToken) {
    if (left.endsWith("\n")) {
      left = left.slice(0, -1);
    }
    if (right.endsWith("\n")) {
      right = right.slice(0, -1);
    }
  }
  return Diff.prototype.equals.call(this, left, right, options);
};
function diffLines(oldStr, newStr, callback) {
  return lineDiff.diff(oldStr, newStr, callback);
}
var sentenceDiff = new Diff();
sentenceDiff.tokenize = function(value) {
  return value.split(/(\S.+?[.!?])(?=\s+|$)/);
};
var cssDiff = new Diff();
cssDiff.tokenize = function(value) {
  return value.split(/([{}:;,]|\s+)/);
};
function _typeof(o) {
  "@babel/helpers - typeof";
  return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function(o2) {
    return typeof o2;
  } : function(o2) {
    return o2 && "function" == typeof Symbol && o2.constructor === Symbol && o2 !== Symbol.prototype ? "symbol" : typeof o2;
  }, _typeof(o);
}
var jsonDiff = new Diff();
jsonDiff.useLongestToken = true;
jsonDiff.tokenize = lineDiff.tokenize;
jsonDiff.castInput = function(value, options) {
  var undefinedReplacement = options.undefinedReplacement, _options$stringifyRep = options.stringifyReplacer, stringifyReplacer = _options$stringifyRep === void 0 ? function(k, v) {
    return typeof v === "undefined" ? undefinedReplacement : v;
  } : _options$stringifyRep;
  return typeof value === "string" ? value : JSON.stringify(canonicalize(value, null, null, stringifyReplacer), stringifyReplacer, "  ");
};
jsonDiff.equals = function(left, right, options) {
  return Diff.prototype.equals.call(jsonDiff, left.replace(/,([\r\n])/g, "$1"), right.replace(/,([\r\n])/g, "$1"), options);
};
function canonicalize(obj, stack, replacementStack, replacer, key) {
  stack = stack || [];
  replacementStack = replacementStack || [];
  if (replacer) {
    obj = replacer(key, obj);
  }
  var i;
  for (i = 0; i < stack.length; i += 1) {
    if (stack[i] === obj) {
      return replacementStack[i];
    }
  }
  var canonicalizedObj;
  if ("[object Array]" === Object.prototype.toString.call(obj)) {
    stack.push(obj);
    canonicalizedObj = new Array(obj.length);
    replacementStack.push(canonicalizedObj);
    for (i = 0; i < obj.length; i += 1) {
      canonicalizedObj[i] = canonicalize(obj[i], stack, replacementStack, replacer, key);
    }
    stack.pop();
    replacementStack.pop();
    return canonicalizedObj;
  }
  if (obj && obj.toJSON) {
    obj = obj.toJSON();
  }
  if (_typeof(obj) === "object" && obj !== null) {
    stack.push(obj);
    canonicalizedObj = {};
    replacementStack.push(canonicalizedObj);
    var sortedKeys = [], _key;
    for (_key in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, _key)) {
        sortedKeys.push(_key);
      }
    }
    sortedKeys.sort();
    for (i = 0; i < sortedKeys.length; i += 1) {
      _key = sortedKeys[i];
      canonicalizedObj[_key] = canonicalize(obj[_key], stack, replacementStack, replacer, _key);
    }
    stack.pop();
    replacementStack.pop();
  } else {
    canonicalizedObj = obj;
  }
  return canonicalizedObj;
}
var arrayDiff = new Diff();
arrayDiff.tokenize = function(value) {
  return value.slice();
};
arrayDiff.join = arrayDiff.removeEmpty = function(value) {
  return value;
};

// src/CleanupModal.ts
var CleanupModal = class extends import_obsidian.Modal {
  constructor(app, originalContent, cleanedContent, summary, onApply, options = {}) {
    super(app);
    this.originalContent = originalContent;
    this.cleanedContent = cleanedContent;
    this.summary = summary;
    this.onApply = onApply;
    this.options = options;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("sweeper-modal");
    const header = contentEl.createDiv({ cls: "sweeper-header" });
    const title = this.options.mode === "paste" ? "Paste cleanup preview" : this.options.mode === "save" ? "Save cleanup preview" : "Sweeper Preview";
    header.createEl("h2", { text: title });
    const summaryText = formatSummary(this.summary);
    header.createEl("p", {
      text: summaryText,
      cls: this.summary.totalChanges > 0 ? "sweeper-summary" : "sweeper-no-changes"
    });
    const diffContainer = contentEl.createDiv({ cls: "sweeper-diff-container" });
    if (this.summary.totalChanges === 0) {
      diffContainer.createEl("p", {
        text: "Your document is already clean!",
        cls: "sweeper-no-changes-message"
      });
    } else {
      this.renderUnifiedDiff(diffContainer);
    }
    const buttonContainer = contentEl.createDiv({ cls: "sweeper-buttons" });
    const mode = this.options.mode;
    if (this.summary.totalChanges > 0) {
      const applyBtn = buttonContainer.createEl("button", {
        text: mode === "paste" || mode === "save" ? "Accept" : "Apply Changes",
        cls: "mod-cta"
      });
      applyBtn.addEventListener("click", () => {
        this.onApply();
        this.close();
      });
    }
    const cancelBtnText = mode === "paste" || mode === "save" ? "Save original" : this.summary.totalChanges > 0 ? "Cancel" : "Close";
    const cancelBtn = buttonContainer.createEl("button", { text: cancelBtnText });
    cancelBtn.addEventListener("click", () => {
      if (mode === "paste" && this.options.onKeepOriginal) {
        this.options.onKeepOriginal();
      }
      this.close();
    });
  }
  renderUnifiedDiff(container) {
    const linePairs = this.computeLinePairs();
    const diffEl = container.createDiv({ cls: "sweeper-diff" });
    if (this.options.isPartial) {
      this.renderEllipsis(diffEl);
    }
    for (const pair of linePairs) {
      if (pair.type === "unchanged") {
        this.renderUnchangedLine(diffEl, pair.oldLine || "");
      } else if (pair.type === "modified") {
        this.renderModifiedPair(diffEl, pair.oldLine || "", pair.newLine || "");
      } else if (pair.type === "removed") {
        this.renderRemovedLine(diffEl, pair.oldLine || "");
      } else if (pair.type === "added") {
        this.renderAddedLine(diffEl, pair.newLine || "");
      }
    }
    if (this.options.isPartial) {
      this.renderEllipsis(diffEl);
    }
  }
  renderEllipsis(container) {
    const lineEl = container.createDiv({ cls: "sweeper-line sweeper-line-ellipsis" });
    lineEl.createSpan({ text: "  ", cls: "sweeper-prefix" });
    lineEl.createSpan({ text: "...", cls: "sweeper-ellipsis" });
  }
  computeLinePairs() {
    const diff2 = diffLines(this.originalContent, this.cleanedContent);
    const pairs = [];
    let i = 0;
    while (i < diff2.length) {
      const part = diff2[i];
      if (!part.added && !part.removed) {
        const lines = this.splitLines(part.value);
        for (const line of lines) {
          pairs.push({ type: "unchanged", oldLine: line });
        }
        i++;
      } else if (part.removed) {
        const removedLines = this.splitLines(part.value);
        const nextPart = diff2[i + 1];
        if (nextPart && nextPart.added) {
          const addedLines = this.splitLines(nextPart.value);
          this.matchAndPairLines(removedLines, addedLines, pairs);
          i += 2;
        } else {
          for (const line of removedLines) {
            pairs.push({ type: "removed", oldLine: line });
          }
          i++;
        }
      } else if (part.added) {
        const addedLines = this.splitLines(part.value);
        for (const line of addedLines) {
          pairs.push({ type: "added", newLine: line });
        }
        i++;
      }
    }
    return pairs;
  }
  matchAndPairLines(removedLines, addedLines, pairs) {
    const addedUsed = /* @__PURE__ */ new Set();
    for (const oldLine of removedLines) {
      const oldTrimmed = oldLine.trim();
      let matchIdx = -1;
      for (let j = 0; j < addedLines.length; j++) {
        if (addedUsed.has(j))
          continue;
        if (addedLines[j].trim() === oldTrimmed) {
          matchIdx = j;
          break;
        }
      }
      if (matchIdx !== -1) {
        const newLine = addedLines[matchIdx];
        addedUsed.add(matchIdx);
        if (oldLine === newLine) {
          pairs.push({ type: "unchanged", oldLine });
        } else {
          pairs.push({ type: "modified", oldLine, newLine });
        }
      } else if (oldTrimmed === "") {
        pairs.push({ type: "removed", oldLine });
      } else {
        let bestIdx = -1;
        let bestScore = 0;
        for (let j = 0; j < addedLines.length; j++) {
          if (addedUsed.has(j))
            continue;
          const score = this.similarity(oldTrimmed, addedLines[j].trim());
          if (score > bestScore && score > 0.5) {
            bestScore = score;
            bestIdx = j;
          }
        }
        if (bestIdx !== -1) {
          addedUsed.add(bestIdx);
          pairs.push({ type: "modified", oldLine, newLine: addedLines[bestIdx] });
        } else {
          pairs.push({ type: "removed", oldLine });
        }
      }
    }
    for (let j = 0; j < addedLines.length; j++) {
      if (!addedUsed.has(j)) {
        pairs.push({ type: "added", newLine: addedLines[j] });
      }
    }
  }
  similarity(a, b) {
    if (a === b)
      return 1;
    if (a.length === 0 || b.length === 0)
      return 0;
    const setA = new Set(a);
    const setB = new Set(b);
    let common = 0;
    for (const c of setA) {
      if (setB.has(c))
        common++;
    }
    return 2 * common / (setA.size + setB.size);
  }
  splitLines(text) {
    const lines = text.split("\n");
    if (lines.length > 0 && lines[lines.length - 1] === "") {
      lines.pop();
    }
    return lines;
  }
  renderUnchangedLine(container, line) {
    const lineEl = container.createDiv({ cls: "sweeper-line sweeper-line-unchanged" });
    lineEl.createSpan({ text: "  ", cls: "sweeper-prefix" });
    lineEl.createSpan({ text: line || " " });
  }
  renderRemovedLine(container, line) {
    const lineEl = container.createDiv({ cls: "sweeper-line sweeper-line-removed" });
    lineEl.createSpan({ text: "- ", cls: "sweeper-prefix" });
    if (line.trim() === "") {
      if (line.length > 0) {
        this.renderVisibleWhitespace(lineEl, line, "sweeper-char-removed");
      }
      lineEl.createSpan({ text: " \u2190 removed", cls: "sweeper-blank-label" });
    } else {
      this.renderLineWithWhitespace(lineEl, line, true);
    }
  }
  renderAddedLine(container, line) {
    const lineEl = container.createDiv({ cls: "sweeper-line sweeper-line-added" });
    lineEl.createSpan({ text: "+ ", cls: "sweeper-prefix" });
    this.renderLineWithWhitespace(lineEl, line, false);
  }
  renderModifiedPair(container, oldLine, newLine) {
    if (this.isWhitespaceOnlyChange(oldLine, newLine)) {
      this.renderWhitespaceOnlyChange(container, oldLine, newLine);
      return;
    }
    const removedEl = container.createDiv({ cls: "sweeper-line sweeper-line-removed" });
    removedEl.createSpan({ text: "- ", cls: "sweeper-prefix" });
    this.renderCharDiff(removedEl, oldLine, newLine, true);
    const addedEl = container.createDiv({ cls: "sweeper-line sweeper-line-added" });
    addedEl.createSpan({ text: "+ ", cls: "sweeper-prefix" });
    this.renderCharDiff(addedEl, oldLine, newLine, false);
  }
  renderWhitespaceOnlyChange(container, oldLine, newLine) {
    var _a, _b, _c, _d;
    const lineEl = container.createDiv({ cls: "sweeper-line sweeper-line-whitespace" });
    lineEl.createSpan({ text: "  ", cls: "sweeper-prefix" });
    const oldLeading = ((_a = oldLine.match(/^[ \t]*/)) == null ? void 0 : _a[0]) || "";
    const newLeading = ((_b = newLine.match(/^[ \t]*/)) == null ? void 0 : _b[0]) || "";
    const oldTrailing = ((_c = oldLine.match(/[ \t]*$/)) == null ? void 0 : _c[0]) || "";
    const newTrailing = ((_d = newLine.match(/[ \t]*$/)) == null ? void 0 : _d[0]) || "";
    const removedLeading = oldLeading.slice(newLeading.length);
    const removedTrailing = oldTrailing.slice(newTrailing.length);
    if (newLine === "" && (removedLeading || removedTrailing)) {
      this.renderVisibleWhitespace(lineEl, oldLine, "sweeper-ws-removed");
      lineEl.createSpan({
        text: ` \u2190 blank lines (${this.summary.results.get("trailingWhitespaceBlank") || 0})`,
        cls: "sweeper-blank-label"
      });
    } else {
      if (removedLeading) {
        this.renderVisibleWhitespace(lineEl, removedLeading, "sweeper-ws-removed");
      }
      lineEl.createSpan({ text: newLine.trim() });
      if (removedTrailing) {
        this.renderVisibleWhitespace(lineEl, removedTrailing, "sweeper-ws-removed");
      }
    }
  }
  renderCharDiff(container, oldLine, newLine, showOld) {
    const charDiff = diffChars(oldLine, newLine);
    const isWhitespaceOnly = this.isWhitespaceOnlyChange(oldLine, newLine);
    for (const part of charDiff) {
      if (showOld) {
        if (part.removed) {
          if (isWhitespaceOnly && /^\s+$/.test(part.value)) {
            this.renderVisibleWhitespace(container, part.value, "sweeper-char-removed");
          } else {
            container.createSpan({
              text: part.value,
              cls: "sweeper-char-removed"
            });
          }
        } else if (!part.added) {
          container.createSpan({ text: part.value });
        }
      } else {
        if (part.added) {
          container.createSpan({
            text: part.value,
            cls: "sweeper-char-added"
          });
        } else if (!part.removed) {
          container.createSpan({ text: part.value });
        }
      }
    }
    if (showOld && oldLine === "" || !showOld && newLine === "") {
      container.createSpan({ text: "(empty line)", cls: "sweeper-empty-line" });
    }
  }
  isWhitespaceOnlyChange(oldLine, newLine) {
    return oldLine.trim() === newLine.trim();
  }
  renderLineWithWhitespace(container, line, highlightTrailing) {
    if (line === "") {
      container.createSpan({ text: "(empty line)", cls: "sweeper-empty-line" });
      return;
    }
    if (highlightTrailing) {
      const match = line.match(/^(.*?)(\s+)$/);
      if (match) {
        container.createSpan({ text: match[1] });
        this.renderVisibleWhitespace(container, match[2], "sweeper-char-removed");
        return;
      }
    }
    container.createSpan({ text: line });
  }
  renderVisibleWhitespace(container, whitespace, cls) {
    let visible = "";
    for (const char of whitespace) {
      if (char === " ") {
        visible += "\xB7";
      } else if (char === "	") {
        visible += "\u2192   ";
      } else {
        visible += char;
      }
    }
    container.createSpan({ text: visible, cls: cls + " sweeper-whitespace" });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/rules/types.ts
var ruleGroups = [
  "blankLines",
  "whitespace",
  "lists",
  "formatting",
  "headings",
  "html",
  "blockElements",
  "obsidian"
];
var ruleGroupNames = {
  blankLines: "Blank lines",
  whitespace: "Whitespace",
  lists: "Lists",
  formatting: "Formatting",
  headings: "Headings",
  html: "HTML",
  blockElements: "Block elements",
  obsidian: "Obsidian-specific"
};

// src/presets.ts
var tierOrder = ["minimal", "standard", "aggressive"];
function getPresetRules(preset) {
  const enabled = {};
  const presetIndex = tierOrder.indexOf(preset);
  for (const rule of rules) {
    const ruleTierIndex = tierOrder.indexOf(rule.tier);
    enabled[rule.id] = ruleTierIndex <= presetIndex;
  }
  return enabled;
}
var presetNames = {
  minimal: "Minimal",
  standard: "Standard",
  aggressive: "Aggressive"
};

// src/settings.ts
function getDefaultSettings() {
  return {
    enabledRules: getPresetRules("standard"),
    collapsedGroups: {},
    cleanOnSaveMode: "off",
    cleanOnPasteMode: "off",
    activePreset: "standard"
  };
}
function migrateSettings(data) {
  if (typeof data.cleanOnSave === "boolean") {
    data.cleanOnSaveMode = data.cleanOnSave ? "quick" : "off";
    delete data.cleanOnSave;
  }
  if (typeof data.cleanOnPaste === "boolean") {
    data.cleanOnPasteMode = data.cleanOnPaste ? "preview" : "off";
    delete data.cleanOnPaste;
  }
}
var SweeperSettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Behavior" });
    new import_obsidian2.Setting(containerEl).setName("Clean on save").setDesc("Clean markdown when you press Cmd/Ctrl+S").addDropdown(
      (dropdown) => dropdown.addOption("off", "Off").addOption("quick", "Quick").addOption("preview", "Preview").setValue(this.plugin.settings.cleanOnSaveMode).onChange(async (value) => {
        this.plugin.settings.cleanOnSaveMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Clean on paste").setDesc("Clean pasted plain text from clipboard").addDropdown(
      (dropdown) => dropdown.addOption("off", "Off").addOption("quick", "Quick").addOption("preview", "Preview").setValue(this.plugin.settings.cleanOnPasteMode).onChange(async (value) => {
        this.plugin.settings.cleanOnPasteMode = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Cleanup Rules" });
    new import_obsidian2.Setting(containerEl).setName("Preset").setDesc("Quick-select rule sets. You can still toggle individual rules after.").addDropdown((dropdown) => {
      dropdown.addOption("minimal", presetNames.minimal).addOption("standard", presetNames.standard).addOption("aggressive", presetNames.aggressive).addOption("custom", "Custom").setValue(this.plugin.settings.activePreset).onChange(async (value) => {
        const preset = value;
        if (preset !== "custom") {
          this.plugin.settings.enabledRules = getPresetRules(preset);
        }
        this.plugin.settings.activePreset = preset;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const rulesByGroup = this.groupRules();
    const allCollapsed = ruleGroups.every((g) => this.plugin.settings.collapsedGroups[g]);
    const collapseBtn = containerEl.createEl("button", {
      text: allCollapsed ? "Expand all" : "Collapse all",
      cls: "sweeper-collapse-btn"
    });
    collapseBtn.addEventListener("click", async () => {
      const newState = !allCollapsed;
      for (const group of ruleGroups) {
        this.plugin.settings.collapsedGroups[group] = newState;
      }
      await this.plugin.saveSettings();
      this.display();
    });
    for (const group of ruleGroups) {
      const groupRules = rulesByGroup.get(group);
      if (!groupRules || groupRules.length === 0)
        continue;
      this.renderGroup(containerEl, group, groupRules);
    }
  }
  groupRules() {
    const grouped = /* @__PURE__ */ new Map();
    for (const rule of rules) {
      const existing = grouped.get(rule.group) || [];
      existing.push(rule);
      grouped.set(rule.group, existing);
    }
    return grouped;
  }
  renderGroup(container, group, groupRules) {
    var _a;
    const isCollapsed = (_a = this.plugin.settings.collapsedGroups[group]) != null ? _a : false;
    const enabledCount = groupRules.filter(
      (r) => {
        var _a2;
        return (_a2 = this.plugin.settings.enabledRules[r.id]) != null ? _a2 : true;
      }
    ).length;
    const groupContainer = container.createDiv({ cls: "sweeper-group" });
    const header = groupContainer.createDiv({ cls: "sweeper-group-header" });
    header.createSpan({
      text: isCollapsed ? "\u25B6 " : "\u25BC ",
      cls: "sweeper-group-arrow"
    });
    header.createSpan({ text: ruleGroupNames[group] });
    header.createSpan({
      text: `${enabledCount} of ${groupRules.length}`,
      cls: "sweeper-group-count"
    });
    const rulesContainer = groupContainer.createDiv({
      cls: "sweeper-group-rules"
    });
    if (isCollapsed) {
      rulesContainer.style.display = "none";
    }
    header.addEventListener("click", async () => {
      const nowCollapsed = !this.plugin.settings.collapsedGroups[group];
      this.plugin.settings.collapsedGroups[group] = nowCollapsed;
      await this.plugin.saveSettings();
      this.display();
    });
    for (const rule of groupRules) {
      new import_obsidian2.Setting(rulesContainer).setName(rule.name).setDesc(rule.example).addToggle(
        (toggle) => {
          var _a2;
          return toggle.setValue((_a2 = this.plugin.settings.enabledRules[rule.id]) != null ? _a2 : true).onChange(async (value) => {
            this.plugin.settings.enabledRules[rule.id] = value;
            this.plugin.settings.activePreset = "custom";
            await this.plugin.saveSettings();
            this.display();
          });
        }
      );
    }
  }
};

// src/main.ts
var SweeperPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.originalCheckCallback = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SweeperSettingsTab(this.app, this));
    this.addRibbonIcon("eraser", "Clean Markdown", () => {
      this.runCleanup();
    });
    this.addCommand({
      id: "cleanup-markdown",
      name: "Clean Markdown",
      editorCallback: (editor) => {
        this.runCleanupWithEditor(editor);
      }
    });
    this.addCommand({
      id: "quick-cleanup",
      name: "Quick Cleanup (no preview)",
      editorCallback: (editor) => {
        this.runQuickCleanup(editor);
      }
    });
    this.addCommand({
      id: "paste-and-clean",
      name: "Paste and Clean",
      editorCallback: (editor) => {
        this.pasteAndClean(editor);
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-paste", this.handlePaste.bind(this))
    );
    this.app.workspace.onLayoutReady(() => {
      this.hookSaveCommand();
    });
  }
  hookSaveCommand() {
    var _a;
    const commands = (_a = this.app.commands) == null ? void 0 : _a.commands;
    const saveCommand = commands == null ? void 0 : commands["editor:save-file"];
    if (saveCommand == null ? void 0 : saveCommand.checkCallback) {
      this.originalCheckCallback = saveCommand.checkCallback;
      saveCommand.checkCallback = (checking) => {
        if (checking) {
          return this.originalCheckCallback(checking);
        }
        this.cleanOnSave(() => this.originalCheckCallback(false));
        return true;
      };
    }
  }
  cleanOnSave(originalSave) {
    var _a;
    if (this.settings.cleanOnSaveMode === "off") {
      originalSave();
      return;
    }
    const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!view || ((_a = view.file) == null ? void 0 : _a.extension) !== "md") {
      originalSave();
      return;
    }
    const editor = view.editor;
    const content = editor.getValue();
    const { content: cleaned, summary } = applyAllRules(content, this.settings.enabledRules);
    if (summary.totalChanges === 0) {
      originalSave();
      return;
    }
    if (this.settings.cleanOnSaveMode === "quick") {
      editor.setValue(cleaned);
      originalSave();
      new import_obsidian3.Notice(`Cleaned ${summary.totalChanges} items`);
      return;
    }
    new CleanupModal(
      this.app,
      content,
      cleaned,
      summary,
      () => {
        editor.setValue(cleaned);
        originalSave();
        new import_obsidian3.Notice(`Cleaned ${summary.totalChanges} items`);
      },
      {
        mode: "save",
        onKeepOriginal: () => {
          originalSave();
        }
      }
    ).open();
  }
  async loadSettings() {
    const data = await this.loadData() || {};
    migrateSettings(data);
    this.settings = Object.assign(getDefaultSettings(), data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  runCleanup() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!view) {
      new import_obsidian3.Notice("No active markdown file");
      return;
    }
    const editor = view.editor;
    this.runCleanupWithEditor(editor);
  }
  runCleanupWithEditor(editor) {
    const selection = editor.getSelection();
    if (selection) {
      this.runCleanupOnSelection(editor, selection);
    } else {
      this.runCleanupOnDocument(editor);
    }
  }
  runCleanupOnDocument(editor) {
    const loadingNotice = new import_obsidian3.Notice("Preparing cleanup...", 0);
    const originalContent = editor.getValue();
    const { content: cleanedContent, summary } = applyAllRules(
      originalContent,
      this.settings.enabledRules
    );
    loadingNotice.hide();
    new CleanupModal(this.app, originalContent, cleanedContent, summary, () => {
      editor.setValue(cleanedContent);
      new import_obsidian3.Notice("Markdown cleaned up!");
    }).open();
  }
  runCleanupOnSelection(editor, selection) {
    const loadingNotice = new import_obsidian3.Notice("Preparing cleanup...", 0);
    const { content: cleanedContent, summary } = applyAllRules(
      selection,
      this.settings.enabledRules
    );
    loadingNotice.hide();
    new CleanupModal(
      this.app,
      selection,
      cleanedContent,
      summary,
      () => {
        editor.replaceSelection(cleanedContent);
        new import_obsidian3.Notice("Selection cleaned up!");
      },
      { isPartial: true }
    ).open();
  }
  runQuickCleanup(editor) {
    const loadingNotice = new import_obsidian3.Notice("Preparing cleanup...", 0);
    const selection = editor.getSelection();
    if (selection) {
      const { content: cleaned, summary } = applyAllRules(selection, this.settings.enabledRules);
      loadingNotice.hide();
      if (summary.totalChanges > 0) {
        editor.replaceSelection(cleaned);
        new import_obsidian3.Notice(`Cleaned ${summary.totalChanges} items in selection`);
      } else {
        new import_obsidian3.Notice("Selection already clean");
      }
    } else {
      const content = editor.getValue();
      const { content: cleaned, summary } = applyAllRules(content, this.settings.enabledRules);
      loadingNotice.hide();
      if (summary.totalChanges > 0) {
        editor.setValue(cleaned);
        new import_obsidian3.Notice(`Cleaned ${summary.totalChanges} items`);
      } else {
        new import_obsidian3.Notice("Document already clean");
      }
    }
  }
  async pasteAndClean(editor) {
    try {
      const clipboard = await navigator.clipboard.readText();
      if (!clipboard) {
        new import_obsidian3.Notice("Clipboard is empty");
        return;
      }
      const loadingNotice = new import_obsidian3.Notice("Preparing cleanup...", 0);
      const { content: cleaned, summary } = applyAllRules(clipboard, this.settings.enabledRules);
      loadingNotice.hide();
      editor.replaceSelection(cleaned);
      if (summary.totalChanges > 0) {
        new import_obsidian3.Notice(`Pasted and cleaned ${summary.totalChanges} items`);
      } else {
        new import_obsidian3.Notice("Pasted (no cleanup needed)");
      }
    } catch (e) {
      new import_obsidian3.Notice("Failed to read clipboard");
    }
  }
  handlePaste(evt, editor) {
    var _a, _b;
    if (this.settings.cleanOnPasteMode === "off")
      return;
    if ((_a = evt.clipboardData) == null ? void 0 : _a.types.includes("text/html"))
      return;
    const original = (_b = evt.clipboardData) == null ? void 0 : _b.getData("text/plain");
    if (!original)
      return;
    evt.preventDefault();
    const loadingNotice = new import_obsidian3.Notice("Preparing cleanup...", 0);
    const { content: cleaned, summary } = applyAllRules(original, this.settings.enabledRules);
    loadingNotice.hide();
    if (summary.totalChanges === 0) {
      editor.replaceSelection(original);
      return;
    }
    if (this.settings.cleanOnPasteMode === "quick") {
      editor.replaceSelection(cleaned);
      new import_obsidian3.Notice(`Pasted with ${summary.totalChanges} cleanups`);
      return;
    }
    new CleanupModal(
      this.app,
      original,
      cleaned,
      summary,
      () => {
        editor.replaceSelection(cleaned);
        new import_obsidian3.Notice(`Pasted with ${summary.totalChanges} cleanups`);
      },
      {
        mode: "paste",
        onKeepOriginal: () => {
          editor.replaceSelection(original);
        }
      }
    ).open();
  }
  onunload() {
    var _a;
    if (this.originalCheckCallback) {
      const commands = (_a = this.app.commands) == null ? void 0 : _a.commands;
      const saveCommand = commands == null ? void 0 : commands["editor:save-file"];
      if (saveCommand) {
        saveCommand.checkCallback = this.originalCheckCallback;
      }
    }
  }
};
