/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HighlightExtractor
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  outputFolder: "3-\u4E13\u4E1A\u5B66\u4E60/\u96C5\u601D/\u751F\u8BCD",
  autoOpenFile: true,
  showNotification: true
};
var HighlightExtractor = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "extract-highlights-from-current-note",
      name: "\u63D0\u53D6\u5F53\u524D\u7B14\u8BB0\u7684\u9AD8\u4EAE\u8BCD\u6C47",
      callback: () => {
        this.extractHighlights();
      }
    });
    this.addCommand({
      id: "extract-and-open-highlights",
      name: "\u63D0\u53D6\u9AD8\u4EAE\u8BCD\u6C47\u5E76\u6253\u5F00\u751F\u8BCD\u672C",
      callback: () => {
        this.extractHighlights(true);
      }
    });
    this.addSettingTab(new HighlightExtractorSettingTab(this.app, this));
    console.log("Highlight Extractor plugin loaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * 从当前笔记提取高亮词汇
   */
  async extractHighlights(openFile = false) {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view) {
      new import_obsidian.Notice("\u274C \u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u7B14\u8BB0");
      return;
    }
    const file = view.file;
    if (!file) {
      new import_obsidian.Notice("\u274C \u65E0\u6CD5\u83B7\u53D6\u5F53\u524D\u6587\u4EF6");
      return;
    }
    try {
      const content = await this.app.vault.read(file);
      const highlights = this.extractHighlightsFromContent(content);
      if (highlights.length === 0) {
        new import_obsidian.Notice("\u2705 \u5F53\u524D\u7B14\u8BB0\u6CA1\u6709\u53D1\u73B0\u9AD8\u4EAE\u8BCD\u6C47\uFF08==text==\u683C\u5F0F\uFF09");
        return;
      }
      const savedFile = await this.saveToFile(highlights);
      if (this.settings.showNotification) {
        new import_obsidian.Notice(`\u2705 \u6210\u529F\u63D0\u53D6 ${highlights.length} \u4E2A\u9AD8\u4EAE\u8BCD\u6C47
\u{1F4C4} \u5DF2\u4FDD\u5B58\u5230: ${savedFile.path}`, 5e3);
      }
      if (openFile || this.settings.autoOpenFile) {
        await this.app.workspace.getLeaf("tab").openFile(savedFile);
      }
    } catch (error) {
      console.error("\u63D0\u53D6\u9AD8\u4EAE\u8BCD\u6C47\u5931\u8D25:", error);
      new import_obsidian.Notice(`\u274C \u63D0\u53D6\u5931\u8D25: ${error.message}`);
    }
  }
  /**
   * 从Markdown内容中提取高亮词汇
   */
  extractHighlightsFromContent(content) {
    const regex = /==([^=]+)==/g;
    const matches = /* @__PURE__ */ new Set();
    let match;
    while ((match = regex.exec(content)) !== null) {
      const word = match[1].trim();
      if (word) {
        matches.add(word);
      }
    }
    return Array.from(matches);
  }
  /**
   * 保存高亮词汇到文件
   */
  async saveToFile(highlights) {
    const outputFolder = this.settings.outputFolder;
    if (!await this.app.vault.adapter.exists(outputFolder)) {
      await this.app.vault.createFolder(outputFolder);
    }
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10);
    const fileName = `${outputFolder}/${dateStr}-\u751F\u8BCD.md`;
    const content = highlights.join("\n") + "\n";
    let file = this.app.vault.getAbstractFileByPath(fileName);
    if (file) {
      const existingContent = await this.app.vault.read(file);
      await this.app.vault.modify(file, existingContent + content);
    } else {
      file = await this.app.vault.create(fileName, content);
    }
    return file;
  }
};
var HighlightExtractorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u9AD8\u4EAE\u8BCD\u6C47\u63D0\u53D6\u5668 - \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u8F93\u51FA\u6587\u4EF6\u5939").setDesc("\u9AD8\u4EAE\u8BCD\u6C47\u4FDD\u5B58\u7684\u76EE\u6807\u8DEF\u5F84\uFF08\u76F8\u5BF9\u8DEF\u5F84\uFF09").addText((text) => text.setPlaceholder("3-\u4E13\u4E1A\u5B66\u4E60/\u96C5\u601D/\u751F\u8BCD").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u6253\u5F00\u751F\u8BCD\u672C").setDesc("\u63D0\u53D6\u5B8C\u6210\u540E\u81EA\u52A8\u6253\u5F00\u751F\u8BCD\u672C\u6587\u4EF6").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOpenFile).onChange(async (value) => {
      this.plugin.settings.autoOpenFile = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u663E\u793A\u901A\u77E5").setDesc("\u5728\u5C4F\u5E55\u53F3\u4E0B\u89D2\u663E\u793A\u6210\u529F\u63D0\u793A").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotification).onChange(async (value) => {
      this.plugin.settings.showNotification = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u4F7F\u7528\u8BF4\u660E" });
    containerEl.createEl("p", { text: "1. \u5728\u7B14\u8BB0\u4E2D\u4F7F\u7528 ==\u9AD8\u4EAE\u6587\u672C== \u683C\u5F0F\u6807\u8BB0\u8BCD\u6C47" });
    containerEl.createEl("p", { text: "2. \u70B9\u51FB\u5DE6\u4FA7\u8FB9\u680F\u7684\u270F\uFE0F\u56FE\u6807\uFF0C\u6216\u4F7F\u7528\u547D\u4EE4\u9762\u677F\uFF08Ctrl/Cmd+P\uFF09" });
    containerEl.createEl("p", { text: "3. \u9AD8\u4EAE\u8BCD\u6C47\u5C06\u81EA\u52A8\u63D0\u53D6\u5E76\u8FFD\u52A0\u5230\u751F\u8BCD\u672C" });
    containerEl.createEl("p", { text: "4. \u6587\u4EF6\u6309\u65E5\u671F\u547D\u540D\uFF1AYYYY-MM-DD-\u751F\u8BCD.md" });
    containerEl.createEl("h3", { text: "\u793A\u4F8B" });
    const exampleBox = containerEl.createEl("div", {
      cls: "highlight-extractor-example"
    });
    exampleBox.style.padding = "10px";
    exampleBox.style.background = "var(--background-secondary)";
    exampleBox.style.borderRadius = "5px";
    exampleBox.style.marginTop = "10px";
    exampleBox.innerHTML = `
<pre style="margin: 0;"><strong>\u8F93\u5165\uFF08\u7B14\u8BB0\uFF09\uFF1A</strong>
The ==refrigeration== machine used ==toxic== chemicals.

<strong>\u8F93\u51FA\uFF08\u751F\u8BCD\u672C\uFF09\uFF1A</strong>
refrigeration
toxic</pre>
		`;
  }
};
